// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account" | "/admin" | "/admin/legacy" | "/cart" | "/club" | "/club/ranks" | "/contact" | "/help" | "/heritage" | "/income-plan" | "/legal/[document]" | "/merchants" | "/pages/[slug]" | "/register" | "/shop" | "/shop/[id]" | "/unsubscribe" | "/worlds/[sector]"
type AppRouteHandlerRoutes = "/api/admin/records" | "/api/admin/session" | "/api/health" | "/api/health/ready" | "/api/newsletter" | "/api/platform/[...path]" | "/api/requests" | "/api/status" | "/api/unsubscribe"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/[[...path]]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[[...path]]": { "path"?: string[]; }
  "/about": {}
  "/account": {}
  "/admin": {}
  "/admin/legacy": {}
  "/api/admin/records": {}
  "/api/admin/session": {}
  "/api/health": {}
  "/api/health/ready": {}
  "/api/newsletter": {}
  "/api/platform/[...path]": { "path": string[]; }
  "/api/requests": {}
  "/api/status": {}
  "/api/unsubscribe": {}
  "/cart": {}
  "/club": {}
  "/club/ranks": {}
  "/contact": {}
  "/help": {}
  "/heritage": {}
  "/income-plan": {}
  "/legal/[document]": { "document": string; }
  "/merchants": {}
  "/pages/[slug]": { "slug": string; }
  "/register": {}
  "/shop": {}
  "/shop/[id]": { "id": string; }
  "/unsubscribe": {}
  "/worlds/[sector]": { "sector": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
