'use client';
import {useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import {ArrowLeft,ArrowRight,Compass,HandHeart,PenNib,ArrowUpRight} from '@phosphor-icons/react';

export interface BusinessSectionsProps {
  onEnquire: (interest: string) => void;
  onStory: () => void;
  onCategory: (index: number) => void;
  onArticle: (index: number) => void;
}
function DirectionArrow(){const locale=useLocale();return locale==='en'?<ArrowRight size={21}/>:<ArrowLeft size={21}/>;}
export function BrandIntroduction({onStory}:Pick<BusinessSectionsProps,'onStory'>){const t=useTranslations('Editorial');return <section className="brand-introduction editorial-section" aria-labelledby="perspective-title"><div className="section-index"><span>01 /</span><p>{t('introLabel')}</p></div><div><h2 id="perspective-title">{t('introTitle')}</h2></div><div className="intro-narrative"><p>{t('introText')}</p><button className="editorial-link" onClick={onStory}>{t('introLink')}<DirectionArrow/></button></div></section>;}
export function TravelCollection({onEnquire}:Pick<BusinessSectionsProps,'onEnquire'>){const t=useTranslations('Editorial');const [selected,setSelected]=useState(0);const destinations=['isfahan','shiraz','yazd'];const key=destinations[selected];return <section className="travel-collection editorial-section" id="journeys" aria-labelledby="journeys-title"><div className="editorial-heading"><div><p className="eyebrow">{t('journeyLabel')}</p><h2 id="journeys-title">{t('journeyTitle')}</h2></div><p>{t('journeyIntro')}</p></div><div className="destination-picker" aria-label={t('journeyTitle')}>{destinations.map((destination,i)=><button key={destination} aria-pressed={selected===i} aria-controls="journey-detail" onClick={()=>setSelected(i)}><span>0{i+1}</span>{t(destination)}<DirectionArrow/></button>)}</div><div className="journey-feature" id="journey-detail"><div className="journey-image"><img src={`/assets/${['tourism.jpg','craft.jpg','hero.jpg'][selected]}`} alt={t(key)} loading="lazy"/><span className="image-caption">{t(key)}</span></div><div className="journey-detail" aria-live="polite"><Compass size={38} weight="thin"/><p className="eyebrow">{t(key)}</p><h3>{t(`${key}Title`)}</h3><p>{t(`${key}Text`)}</p><button className="editorial-link" onClick={()=>onEnquire(t(key))}>{t('journeyAction')}<DirectionArrow/></button><small>{t('journeyNote')}</small></div></div></section>;}
export function CraftBeauty({onEnquire,onCategory}:Pick<BusinessSectionsProps,'onEnquire'|'onCategory'>){const t=useTranslations('Editorial');return <section className="craft-beauty editorial-section" aria-labelledby="craft-title"><div className="craft-editorial"><div className="craft-visual"><img src="/assets/craft.jpg" alt={t('craftCaption')} loading="lazy"/><span>HOMAY SAADAT / CRAFT</span></div><div className="craft-story"><p className="eyebrow">{t('craftLabel')}</p><h2 id="craft-title">{t('craftTitle')}</h2><p>{t('craftText')}</p><button className="editorial-link" onClick={()=>onEnquire(t('craftTitle'))}>{t('craftAction')}<DirectionArrow/></button><img src="/assets/craft-wide.jpg" alt={t('craftCaption')} loading="lazy"/></div></div><div className="beauty-editorial"><div><HandHeart size={36} weight="thin"/><p className="eyebrow">{t('beautyLabel')}</p><h2>{t('beautyTitle')}</h2><p>{t('beautyText')}</p><button className="editorial-link" onClick={()=>onCategory(1)}>{t('beautyAction')}<DirectionArrow/></button></div><img src="/assets/beauty.jpg" alt={t('beautyLabel')} loading="lazy"/></div></section>;}
export function CreativeStudio({onEnquire}:Pick<BusinessSectionsProps,'onEnquire'>){const t=useTranslations('Editorial');return <section className="creative-studio editorial-section" id="creative-studio" aria-labelledby="studio-title"><div className="studio-monogram"><PenNib size={52} weight="thin"/><p className="eyebrow">{t('studioLabel')}</p><h2 id="studio-title">{t('studioTitle')}</h2></div><div className="studio-details"><p>{t('studioText')}</p><div className="studio-services">{[1,2,3].map(i=><button key={i} onClick={()=>onEnquire(t(`studioService${i}`))}><span>0{i}</span>{t(`studioService${i}`)}<DirectionArrow/></button>)}</div><button className="gold-button" onClick={()=>onEnquire(t('studioLabel'))}>{t('studioAction')}<DirectionArrow/></button></div></section>;}
export function Journal({onArticle}:Pick<BusinessSectionsProps,'onArticle'>){const t=useTranslations('Editorial');return <section className="journal editorial-section" id="journal" aria-labelledby="journal-title"><div className="editorial-heading"><div><p className="eyebrow">{t('journalLabel')}</p><h2 id="journal-title">{t('journalTitle')}</h2></div><span className="journal-edition">HOMAY SAADAT / JOURNAL</span></div><div className="journal-grid">{[1,2,3].map((i)=><article key={i}><button onClick={()=>onArticle(i)}><div className="journal-image"><img src={`/assets/${['tourism.jpg','craft.jpg','ai.jpg'][i-1]}`} alt={t(`journal${i}Title`)} loading="lazy"/><span><ArrowUpRight size={24}/></span></div><p className="eyebrow">{t(`journal${i}Tag`)}</p><h3>{t(`journal${i}Title`)}</h3><span className="journal-read">{t('read')}<DirectionArrow/></span></button></article>)}</div></section>;}
export function BusinessPartnership({onEnquire}:Pick<BusinessSectionsProps,'onEnquire'>){const t=useTranslations('Editorial');return <section className="business-partnership editorial-section" id="partnership" aria-labelledby="business-title"><div><p className="eyebrow">{t('businessLabel')}</p><h2 id="business-title">{t('businessTitle')}</h2></div><div><p>{t('businessText')}</p><button className="editorial-link" onClick={()=>onEnquire(t('partnership'))}>{t('businessAction')}<DirectionArrow/></button></div></section>;}
export function EnquiryProcess(){const t=useTranslations('Editorial');return <section className="enquiry-process editorial-section" aria-labelledby="process-title"><h2 id="process-title">{t('processTitle')}</h2><div>{[1,2,3].map(i=><article key={i}><span>0{i}</span><h3>{t(`process${i}`)}</h3><p>{t(`process${i}Body`)}</p></article>)}</div></section>;}
