export const editorialCopy = {
  "fa": {
    "cmsError": "محتوای تازه دریافت نشد.", "cmsRetry": "تلاش دوباره", "cmsRead": "بیشتر بخوانید", "cmsTitle": "تازه‌های مجموعه",
    "account": "حساب کاربری",
    "collection": "مجموعهٔ همای سعادت",
    "utility": "از ایران، با نگاهی جهانی",
    "partnership": "همکاری با ما",
    "introLabel": "دربارهٔ همای",
    "introTitle": "یک باشگاه،\nهمهٔ خدمات همای.",
    "introText": "همای سعادت در زمینهٔ گردشگری، صنایع‌دستی، محصولات چرمی، زیبایی و فناوری فعالیت می‌کند. با عضویت در باشگاه مشتریان، از همهٔ این خدمات با مزایای ویژهٔ اعضا استفاده می‌کنید و سفارش‌ها و درخواست‌هایتان را در یک حساب کاربری پیگیری می‌کنید.",
    "introLink": "آشنایی با همای سعادت",
    "journeyLabel": "سفر، به روایت شما",
    "journeyTitle": "ایران را نزدیک‌تر ببینید.",
    "journeyIntro": "از قدم‌زدن در شهر تا دیدن هنر در کارگاه؛ علاقه‌تان را انتخاب کنید تا گفت‌وگو دربارهٔ سفر از همان‌جا شروع شود.",
    "isfahan": "معماری و شهر",
    "shiraz": "هنر و کارگاه",
    "yazd": "زندگی و فرهنگ",
    "isfahanTitle": "میدان، بازار، مکث.",
    "shirazTitle": "از نزدیک، کنار هنر دست.",
    "yazdTitle": "فرصتی برای دیدن زندگی.",
    "isfahanText": "برای علاقه‌مندان به معماری، عکاسی و صنایع‌دستی؛ نقطهٔ شروعی برای برنامه‌ریزی سفری که زمان کافی برای دیدن دارد.",
    "shirazText": "اگر دیدن مراحل ساخت یک اثر برایتان جذاب است، علاقه‌تان به هنر و کارگاه را در درخواست سفر بنویسید.",
    "yazdText": "برای تجربهٔ فضاهای شهری و آشنایی با فرهنگ روزمره، از ریتم سفر و علاقه‌های شخصی‌تان بگویید.",
    "journeyAction": "دربارهٔ این سفر گفت‌وگو کنیم",
    "journeyNote": "ایدهٔ سفر؛ برنامه و امکان اجرا پس از بررسی درخواست مشخص می‌شود.",
    "craftLabel": "اشیایی با قصه",
    "craftTitle": "هنر دست، برای زندگی امروز.",
    "craftText": "به رنگ، بافت و رد دست سازنده نگاه کنید. برای انتخاب یک اثر شخصی یا هدیهٔ سازمانی، از سلیقه و کاربرد مورد نظرتان شروع می‌کنیم.",
    "craftAction": "درخواست انتخاب اثر",
    "craftCaption": "رنگ، بافت و جزئیات؛ زبان مشترک یک اثر.",
    "beautyLabel": "زیبایی و مراقبت",
    "beautyTitle": "زمانی برای خودتان.",
    "beautyText": "انتخاب محصولات و تجربه‌های مراقبتی از شناخت سلیقه و نیاز شما شروع می‌شود. دربارهٔ چیزی که دنبالش هستید بنویسید تا درخواستتان در مسیر مرتبط بررسی شود.",
    "beautyAction": "کشف دنیای زیبایی",
    "studioLabel": "استودیو خلاق",
    "studioTitle": "از یک ایده،\nتا روایتی دیدنی.",
    "studioText": "برای برندهایی که حرفی برای گفتن دارند؛ از جهت بصری و محتوای چندزبانه تا بررسی کاربرد ابزارهای هوشمند در جریان کار.",
    "studioAction": "دربارهٔ پروژه‌تان بگویید",
    "studioService1": "هویت و روایت بصری",
    "studioService2": "محتوای چندزبانه",
    "studioService3": "فرآیندهای هوشمند",
    "journalLabel": "دفتر همای سعادت",
    "journalTitle": "چیزهایی که ارزش دیدن دارند.",
    "read": "خواندن یادداشت",
    "journal1Title": "سفر خوب، جایی برای مکث دارد.",
    "journal1Tag": "یادداشت سفر",
    "journal1Body": "برای برنامه‌ریزی سفر لازم نیست همهٔ ساعت‌ها را پر کنیم. گاهی یک صبح آزاد، فرصت دیدن جزئیاتی را می‌دهد که در مسیرهای شلوغ از دست می‌روند. پیش از انتخاب مقصد، از خودمان بپرسیم دوست داریم در سفر چه احساسی داشته باشیم: آرامش، کشف یا همراهی؟ پاسخ همین پرسش، شروع بهتری برای گفت‌وگو دربارهٔ مسیر است.",
    "journal2Title": "هدیه‌ای که فقط زیبا نیست.",
    "journal2Tag": "هنر و زندگی",
    "journal2Body": "یک هدیهٔ دست‌ساز با رنگ و شکلش آغاز می‌شود، اما انتخاب خوب به آدمی که آن را دریافت می‌کند هم فکر می‌کند. کاربرد روزمره، فضای خانه و سلیقهٔ او، به اندازهٔ ظاهر اثر مهم‌اند. برای سفارش هدیهٔ سازمانی هم بهتر است تعداد، زمان مورد نیاز و شیوهٔ بسته‌بندی از ابتدا روشن باشند.",
    "journal3Title": "جزئیات کوچک، روایت بزرگ.",
    "journal3Tag": "نگاه خلاق",
    "journal3Body": "پیش از انتخاب رنگ یا ساختن تصویر، باید بدانیم با چه کسی حرف می‌زنیم. یک روایت منسجم از شناخت مخاطب، هدف روشن و انتخاب دقیق جزئیات شکل می‌گیرد. ابزارها می‌توانند کار را سریع‌تر کنند؛ اما لحن، معنا و کیفیت نهایی به تصمیم‌های سنجیده نیاز دارند.",
    "businessLabel": "همکاری تجاری",
    "businessTitle": "همکاری خوب،\nاز گفت‌وگوی خوب شروع می‌شود.",
    "businessText": "برای همکاری در گردشگری، معرفی آثار، هدایای سازمانی یا پروژه‌های محتوا، زمینهٔ فعالیت و نیازتان را بنویسید. درخواست شما با موضوع مشخص ثبت و قابل پیگیری می‌شود.",
    "businessAction": "ثبت درخواست همکاری",
    "processTitle": "از آشنایی تا قدم بعدی",
    "process1": "علاقه‌تان را انتخاب کنید",
    "process1Body": "حوزه، مقصد یا ایده‌ای را که در ذهن دارید مشخص کنید.",
    "process2": "جزئیات را با ما در میان بگذارید",
    "process2Body": "زمان، نیازها و اولویت‌ها را در درخواست بنویسید.",
    "process3": "درخواستتان را پیگیری کنید",
    "process3Body": "رسید را نگه دارید و وضعیت بررسی را با کد خصوصی ببینید.",
    "footerTitle": "در ارتباط بمانیم.",
    "footerText": "برای یک پرسش، یک سفر یا شروع همکاری؛ از همین‌جا به ما بگویید.",
    "footerContact": "گفت‌وگو با همای سعادت",
    "footerIdentity": "سفر · زیبایی · فرهنگ · خلاقیت",
    "viewAll": "همهٔ حوزه‌ها",
    "discover": "کشف کنید"
  },
  "en": {
    "cmsError": "Updates could not be loaded.", "cmsRetry": "Try again", "cmsRead": "Read more", "cmsTitle": "Latest from Homay Saadat",
    "account": "My account",
    "collection": "The Homay Saadat collection",
    "utility": "Rooted in Iran. Open to the world.",
    "partnership": "Partner with us",
    "introLabel": "ABOUT HOMA",
    "introTitle": "One club.\nEvery Homa service.",
    "introText": "Homay Saadat works across travel, handicrafts, leather goods, beauty and technology. As a member of the customers club, you use all of these services with member benefits and follow your orders and requests from a single account.",
    "introLink": "Meet Homay Saadat",
    "journeyLabel": "TRAVEL, YOUR WAY",
    "journeyTitle": "A closer look at Iran.",
    "journeyIntro": "From a walk through the city to time in a craft workshop. Choose what draws you in, and let that be the beginning of a conversation about your journey.",
    "isfahan": "Architecture and city life",
    "shiraz": "Craft & workshops",
    "yazd": "Life & culture",
    "isfahanTitle": "A square. A bazaar. A slower pace.",
    "shirazTitle": "Closer to the making.",
    "yazdTitle": "Time to notice everyday life.",
    "isfahanText": "For an interest in architecture, photography and craftsmanship. A starting point for a journey with time to notice the details.",
    "shirazText": "Interested in how an object takes shape? Include your interest in craft and workshops in your travel enquiry.",
    "yazdText": "For an interest in city spaces and everyday culture, tell us about the pace and experiences you have in mind.",
    "journeyAction": "Enquire about this journey",
    "journeyNote": "Travel inspiration; itinerary and availability are confirmed after review.",
    "craftLabel": "OBJECTS WITH A STORY",
    "craftTitle": "Made by hand. Chosen for life.",
    "craftText": "Look at the colour, the texture, the hand behind the work. Whether you are considering a personal piece or a business gift, start with how you want it to feel and where it will belong.",
    "craftAction": "Discuss a piece",
    "craftCaption": "Colour, texture and detail. The language of a piece.",
    "beautyLabel": "Beauty and care",
    "beautyTitle": "A little time for yourself.",
    "beautyText": "Thoughtful care begins with understanding your preferences. Tell us what you are looking for so your enquiry can be reviewed in the right context.",
    "beautyAction": "Explore beauty & care",
    "studioLabel": "THE CREATIVE STUDIO",
    "studioTitle": "From a first thought\nto something worth seeing.",
    "studioText": "For brands with something to say. Explore visual direction, multilingual content and the considered use of intelligent tools in your creative workflow.",
    "studioAction": "Tell us about your project",
    "studioService1": "Visual identity and storytelling",
    "studioService2": "Multilingual content",
    "studioService3": "Intelligent workflows",
    "journalLabel": "THE JOURNAL",
    "journalTitle": "Worth a closer look.",
    "read": "Read the note",
    "journal1Title": "A good journey leaves time to pause.",
    "journal1Tag": "TRAVEL NOTES",
    "journal1Body": "A well-planned journey does not need to fill every hour. An open morning can leave space for the details a hurried itinerary misses. Before choosing a route, ask what you would like the journey to feel like: restful, curious, shared? That answer is often a useful place to begin.",
    "journal2Title": "A gift with something to say.",
    "journal2Tag": "CRAFT & LIVING",
    "journal2Body": "A handmade gift begins with colour and form, but a thoughtful choice also considers the person receiving it. Everyday use, their home and their preferences matter as much as appearance. For a business gifting enquiry, include the quantity, timing and packaging you have in mind.",
    "journal3Title": "Small details, a clearer story.",
    "journal3Tag": "CREATIVE PERSPECTIVES",
    "journal3Body": "Before selecting a colour or making an image, know who you are speaking to. A coherent story begins with an audience, a clear purpose and a considered choice of details. Tools can make the work faster; voice, meaning and the final quality still depend on deliberate decisions.",
    "businessLabel": "FOR BUSINESSES",
    "businessTitle": "Good partnerships\nbegin with a conversation.",
    "businessText": "For travel partnerships, craft sourcing, business gifts or content projects, tell us about your organisation and what you need. Your enquiry will be recorded with a private reference for follow-up.",
    "businessAction": "Discuss a partnership",
    "processTitle": "A clear next step",
    "process1": "Choose your interest",
    "process1Body": "Start with the experience, destination or idea you have in mind.",
    "process2": "Tell us the details",
    "process2Body": "Include your timing, needs and priorities in the enquiry.",
    "process3": "Follow your enquiry",
    "process3Body": "Keep your receipt and use its private code to check the review status.",
    "footerTitle": "Let’s stay connected.",
    "footerText": "A question, a journey, a new collaboration. Tell us where you would like to begin.",
    "footerContact": "Speak with Homay Saadat",
    "footerIdentity": "TRAVEL · BEAUTY · CULTURE · CREATIVITY",
    "viewAll": "All sectors",
    "discover": "Discover"
  },
  "ar": {
    "cmsError": "تعذر تحميل المستجدات.", "cmsRetry": "حاول مجدداً", "cmsRead": "اقرأ المزيد", "cmsTitle": "آخر المستجدات",
    "account": "حسابي",
    "collection": "مجموعة هماي سعادت",
    "utility": "من إيران، برؤية عالمية",
    "partnership": "تعاون معنا",
    "introLabel": "عن همای",
    "introTitle": "نادٍ واحد.\nكل خدمات هماي.",
    "introText": "تعمل هماي سعادت في مجالات السياحة والحرف اليدوية والمنتجات الجلدية والجمال والتكنولوجيا. بعضويتك في نادي العملاء تستفيد من جميع هذه الخدمات بمزايا خاصة بالأعضاء، وتتابع طلباتك واستفساراتك من حساب واحد.",
    "introLink": "تعرّف إلى هماي سعادت",
    "journeyLabel": "السفر بطريقتك",
    "journeyTitle": "اكتشف إيران عن قرب.",
    "journeyIntro": "من جولة في المدينة إلى زيارة ورشة حرفية. اختر ما يثير اهتمامك لنبدأ الحديث عن رحلتك.",
    "isfahan": "العمارة والمدينة",
    "shiraz": "الحرف والورش",
    "yazd": "الحياة والثقافة",
    "isfahanTitle": "ساحة، سوق، ولحظة تأمل.",
    "shirazTitle": "عن قرب، مع الحِرفة.",
    "yazdTitle": "وقت لاكتشاف تفاصيل الحياة.",
    "isfahanText": "لمهتمّي العمارة والتصوير والحرف؛ بداية لرحلة تمنحك وقتاً لملاحظة التفاصيل.",
    "shirazText": "هل يهمك التعرف إلى مراحل صناعة قطعة يدوية؟ أخبرنا عن اهتمامك بالحرف والورش في طلب رحلتك.",
    "yazdText": "إذا كنت مهتماً بالمدينة وثقافتها اليومية، أخبرنا بإيقاع الرحلة والتجارب التي تفضلها.",
    "journeyAction": "استفسر عن هذه الرحلة",
    "journeyNote": "فكرة للسفر؛ يُحدّد البرنامج والتوافر بعد مراجعة الطلب.",
    "craftLabel": "قطع تحمل حكاية",
    "craftTitle": "صُنعت باليد، لترافق الحياة.",
    "craftText": "تأمّل اللون والملمس وأثر يد الصانع. لاختيار قطعة شخصية أو هدية مؤسسية، نبدأ بذوقك وطريقة استخدامها.",
    "craftAction": "استفسر عن قطعة",
    "craftCaption": "اللون والملمس والتفاصيل؛ لغة القطعة.",
    "beautyLabel": "الجمال والعناية",
    "beautyTitle": "وقتٌ لنفسك.",
    "beautyText": "تبدأ العناية بفهم تفضيلاتك. أخبرنا عمّا تبحث عنه لتُراجع رغبتك في السياق المناسب.",
    "beautyAction": "اكتشف عالم الجمال",
    "studioLabel": "الاستوديو الإبداعي",
    "studioTitle": "من فكرة أولى\nإلى حكاية تستحق المشاهدة.",
    "studioText": "للعلامات التي تحمل رسالة؛ من التوجّه البصري والمحتوى متعدد اللغات إلى الاستخدام المدروس للأدوات الذكية.",
    "studioAction": "حدّثنا عن مشروعك",
    "studioService1": "التوجّه البصري",
    "studioService2": "محتوى متعدد اللغات",
    "studioService3": "عمليات ذكية",
    "journalLabel": "دفتر هماي سعادت",
    "journalTitle": "تستحق نظرة أقرب.",
    "read": "اقرأ المقال",
    "journal1Title": "اترك مساحة للمفاجأة.",
    "journal1Tag": "ملاحظات سفر",
    "journal1Body": "لا تحتاج الرحلة المدروسة إلى ملء كل ساعة. صباح بلا جدول قد يتيح ملاحظة تفاصيل يفوتها المسار المتعجل. قبل اختيار الطريق، اسأل نفسك: هل تريد الهدوء، أم الاكتشاف، أم المشاركة؟ الإجابة بداية مناسبة للتخطيط.",
    "journal2Title": "هدية تحمل معنى.",
    "journal2Tag": "الحرفة والحياة",
    "journal2Body": "تبدأ الهدية اليدوية باللون والشكل، لكن الاختيار المدروس يراعي من يتلقّاها أيضاً. الاستخدام اليومي والمنزل والذوق مهمة بقدر المظهر. لطلب هدايا مؤسسية، حدّد العدد والموعد والتغليف المطلوب.",
    "journal3Title": "تفاصيل صغيرة، حكاية أوضح.",
    "journal3Tag": "رؤى إبداعية",
    "journal3Body": "قبل اختيار لون أو صناعة صورة، اعرف من تخاطب. تبدأ الحكاية المتماسكة بجمهور وهدف واضح وتفاصيل مختارة بعناية. قد تسرّع الأدوات العمل، لكن النبرة والمعنى والجودة تحتاج قرارات مدروسة.",
    "businessLabel": "للشركات",
    "businessTitle": "يبدأ التعاون الجيد\nبحوار جيد.",
    "businessText": "للتعاون السياحي أو الأعمال الحرفية أو الهدايا المؤسسية أو مشاريع المحتوى، أخبرنا عن مؤسستك واحتياجك. يُسجّل طلبك برمز خاص للمتابعة.",
    "businessAction": "ناقش فرصة تعاون",
    "processTitle": "خطوة تالية واضحة",
    "process1": "اختر اهتمامك",
    "process1Body": "ابدأ بالتجربة أو الوجهة أو الفكرة التي في ذهنك.",
    "process2": "شاركنا التفاصيل",
    "process2Body": "اذكر الموعد والاحتياجات والأولويات في طلبك.",
    "process3": "تابع طلبك",
    "process3Body": "احتفظ بالإيصال واستخدم رمزه الخاص لمعرفة حالة المراجعة.",
    "footerTitle": "لنبقَ على تواصل.",
    "footerText": "لسؤال أو رحلة أو تعاون جديد، أخبرنا من أين تريد أن تبدأ.",
    "footerContact": "تواصل مع هماي سعادت",
    "footerIdentity": "سفر · جمال · ثقافة · إبداع",
    "viewAll": "كل مجالاتنا",
    "discover": "اكتشف"
  }
} as const;
