'use client';
import ResponsiveImage from "../src/components/media/ResponsiveImage";

import {useEffect,useRef,useState} from 'react';
import {useLocale} from 'next-intl';
const source='https://upload.wikimedia.org/wikipedia/commons/5/53/Persepolis%2C_Hauptstadt_Persiens_%28CC_BY-SA_4.0%29.webm';
const words={fa:{play:'پخش ویدئو',pause:'توقف ویدئو',video:'بازسازی تخت‌جمشید · Terra X · CC BY-SA 4.0',fallback:'نمای هنری تخت‌جمشید',label:'میراثی که آینده می‌سازد',title:'از شکوه پارسه تا پرواز سیمرغ',intro:'ایران برای ما تنها یک مقصد نیست؛ زبان مشترک هنر، خرد و مهمان‌نوازی است. این روایت، الهام‌بخش خانواده همای سعادت است.',more:'روایت کامل ایران و نمادها',names:['کوروش؛ آغاز یک روایت','شیردال؛ قدرت و ظرافت','سیمرغ؛ خرد و همراهی'],texts:['پاسارگاد و میراث هخامنشی؛ پیوند تاریخ، معماری و تنوع فرهنگی.','برداشتی هنری از پیکره شیر و بال و سر عقاب در زبان نقش‌های کهن.','پرنده اساطیری داستان‌های ایرانی؛ الهام‌بخش یادگیری و بالیدن در کنار یکدیگر.'],art:'بازآفرینی هنری',income:'طرح درآمد'},en:{play:'Play film',pause:'Pause film',video:'Persepolis reconstruction · Terra X · CC BY-SA 4.0',fallback:'Persepolis artwork',label:'HERITAGE, LOOKING FORWARD',title:'From Persepolis to the flight of Simurgh',intro:'Iran is more than a destination. Its art, wisdom and hospitality inspire the Homay Saadat family.',more:'Explore the stories and symbols',names:['Cyrus · a story begins','Griffin · strength and craft','Simurgh · wisdom and belonging'],texts:['Pasargadae and Achaemenid heritage connect architecture, history and cultural diversity.','An artistic interpretation of the winged lion with an eagle’s head.','A mythical bird from Persian literature, inspiring learning and shared growth.'],art:'Artistic interpretation',income:'Income plan'},ar:{play:'تشغيل الفيديو',pause:'إيقاف الفيديو',video:'إعادة بناء برسبوليس · Terra X · CC BY-SA 4.0',fallback:'تصور فني لبرسبوليس',label:'تراث يصنع المستقبل',title:'من روعة برسبوليس إلى تحليق السيمرغ',intro:'إيران أكثر من وجهة؛ فنها وحكمتها وضيافتها تلهم عائلة هماي سعادت.',more:'اكتشف القصص والرموز',names:['كورش؛ بداية الحكاية','الغريفين؛ القوة والفن','السيمرغ؛ الحكمة والرفقة'],texts:['باسارغاد والتراث الأخميني يجمعان التاريخ والعمارة والتنوع الثقافي.','تصور فني لكائن بجسم أسد مجنح ورأس نسر.','طائر أسطوري من الأدب الفارسي، يلهم التعلم والنمو معاً.'],art:'تصور فني',income:'خطة الدخل'}};
export function IncomeMenuLink(){const l=useLocale() as keyof typeof words;return <><a className="income-menu-link" href="/income-plan">{words[l].income}</a><a className="income-menu-link" href="/club/ranks">{l==='en'?'Club ranks':l==='ar'?'رتب النادي':'رتبه‌های باشگاه'}</a></>}
export function HeritageHero(){const l=useLocale() as keyof typeof words,c=words[l];const ref=useRef<HTMLVideoElement>(null),[enabled,setEnabled]=useState(false),[playing,setPlaying]=useState(false),[failed,setFailed]=useState(false);useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)');const allowed=!m.matches&&!(navigator as Navigator&{connection?:{saveData?:boolean}}).connection?.saveData;setEnabled(allowed);const change=()=>{if(m.matches){ref.current?.pause();setPlaying(false);setEnabled(false);}};m.addEventListener('change',change);const visibility=()=>{if(document.hidden)ref.current?.pause();};document.addEventListener('visibilitychange',visibility);return()=>{m.removeEventListener('change',change);document.removeEventListener('visibilitychange',visibility);};},[]);async function toggle(){if(playing){ref.current?.pause();return;}setFailed(false);setEnabled(true);if(ref.current)try{await ref.current.play();}catch{setPlaying(false);}}
return <><ResponsiveImage className="hero-photo" src="/assets/heritage/persepolis.webp" alt={c.fallback} fetchPriority="high"/>{enabled&&!failed&&<video ref={ref} className="heritage-hero-video" autoPlay muted loop playsInline preload="none" poster="/assets/heritage/persepolis.webp" aria-label={c.video} onPlaying={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>{setFailed(true);setPlaying(false);}}><source src={process.env.NEXT_PUBLIC_HERO_VIDEO_URL||source}/></video>}<div className="heritage-video-controls"><button type="button" onClick={toggle} aria-pressed={playing}>{playing?c.pause:c.play}</button><a href="/heritage#media-credit">{playing?c.video:c.fallback}</a></div></>}
export function HeritageSections(){const l=useLocale() as keyof typeof words,c=words[l];return <section className="heritage-section editorial-section" id="heritage"><header><p className="eyebrow">{c.label}</p><h2>{c.title}</h2><p>{c.intro}</p></header><div className="heritage-grid">{['cyrus','griffin','simurgh'].map((key,i)=><article key={key}><a href={'/heritage#'+key}><div className="heritage-visual"><ResponsiveImage src={'/assets/heritage/'+key+'.webp'} alt={c.names[i]+' · '+c.art} sizes="(max-width: 600px) 90vw, (max-width: 1000px) 44vw, 28vw" loading="lazy"/><span className="brand-seal" aria-hidden="true"><ResponsiveImage src="/assets/brand-mark.png" alt=""/>HOMAY SAADAT</span></div><div className="heritage-card-copy"><small>0{i+1} · {c.art}</small><h3>{c.names[i]}</h3><p>{c.texts[i]}</p></div></a></article>)}</div><a className="editorial-link" href="/heritage">{c.more} ↗</a></section>}
