export const copy = {
 en: {
 nav:['Home','Tourism','Beauty','Handicrafts','AI Studio',"Our Story",'Contact'], join:'Join Our Club', menu:'Open menu', close:'Close',
 eyebrow:"LOYALTY CLUB", hero:'Homanet', sub:'Travel. Beauty. Culture. A Brighter Tomorrow.', line:'A journey inspired by beauty, culture, and what comes next.', explore:'Explore the World', story:'Our Story', quote:'Beauty is a bridge between cultures.',
 values:['Authentic Experiences','A More Beautiful You','Timeless Craftsmanship','Creative Future'],
 worlds:'Four Worlds, One Vision', worldsSub:'Where the soul of Persia meets a brighter, more beautiful tomorrow.',
 titles:['Tourism','Beauty','Handicrafts','AI Studio'], descriptions:['Extraordinary journeys into the heart of Iran.','Natural elegance, thoughtful rituals. A more beautiful you.','Timeless art. Living heritage. Made by hand, kept for generations.','Where imagination meets new possibilities.'],
 gallery:'Moments Like Poetry', gallerySub:'Persian beauty. A global perspective.', viewGallery:'View gallery',
 club:'Homanet Club', clubSub:'More beauty. Deeper connections. A kinder world.', perks:['Exclusive experiences','Thoughtful discoveries','A global community'],
 international:'From Iran to Your World', internationalSub:'Discover Dalarit, our vision for bringing Iranian craftsmanship and culture closer to the world.', learn:'Explore International',
 voices:'A Shared Love of Beauty', voicesSub:'The values behind every experience.', quotes:['Travel slowly. Meet the people. Take the stories home.','Beauty begins with care — for ourselves and the world around us.','An object made by hand carries a story worth keeping.'], quoteNames:['A deeper way to travel','A more thoughtful ritual','A living heritage'],
 storyTitle:"Rooted in Iran, open to the world.", storyBody:'Homanet brings travel, beauty, craftsmanship, and creative technology into one shared world. Our inspiration comes from Persian culture: generous hospitality, a love of detail, and the belief that beauty connects people.',
 plan:'Create your experience', choose:'What would you like to discover?', name:'Your name', email:'Email address', message:'Tell us a little more', send:'Prepare my request', requestNote:'Preview form: your details are not sent or stored. Submit to review your request.', success:'Your request is ready to review', successBody:'This preview has prepared your request locally. Nothing has been sent.', again:'Edit request',
 tourismItems:['Isfahan & its living heritage','Shiraz, gardens & poetry','Persepolis & ancient Persia','Yazd, wind & light'], beautyItems:['Everyday beauty rituals',"Inspired by nature",'Personal wellbeing','Mindful self-care'], craftItems:["Pottery and enamelling",'Handwoven carpets','Traditional copperware','Persian textiles'], aiItems:['AI Content Studio','Smart visual design','Multilingual storytelling','Creative automation'],
 detailSub:'Choose an experience to begin shaping your own journey.', next:'Next image', previous:'Previous image', galleryLabel:'Photo gallery', picture:'Photograph', currency:'Currency',
 about:'About Homanet', preview:'Membership preview', clubBody:'Discover the experiences, new collections, and cultural stories you would like to hear about. Choose your interests and prepare your membership enquiry.', contact:'Start a conversation', footerNotice:'Newsletter subscriptions open soon.', formInterest:'Your interest', selected:'Selected experience'
 },
 fa: {
 nav:['خانه','گردشگری','زیبایی','صنایع‌دستی','استودیو هوش مصنوعی','داستان ما','تماس'], join:'به باشگاه ما بپیوندید',menu:'باز کردن منو',close:'بستن',
 eyebrow:'باشگاه مشتریان',hero:'هما نت',sub:'سفر، زیبایی، فرهنگ؛ فردایی روشن‌تر.',line:'سفری به سوی زیبایی، با الهام از فرهنگ و آینده.',explore:'جهان ما را کشف کنید',story:'داستان ما',quote:'زیبایی، پلی میان فرهنگ‌هاست.',
 values:['تجربه‌های اصیل','زیبایی بیشتر شما','هنر ماندگار','آینده‌ای خلاقانه'],worlds:'چهار جهان، یک چشم‌انداز',worldsSub:'جایی که روح ایران با فردایی زیباتر پیوند می‌خورد.',titles:['گردشگری','زیبایی','صنایع‌دستی','استودیو هوش مصنوعی'],descriptions:['سفرهایی متفاوت به قلب ایران؛ فراتر از دیدن، برای تجربه کردن.','زیبایی طبیعی و آیین‌های مراقبت؛ فرصتی برای خودتان.','هنر ماندگار و میراث زنده؛ ساختهٔ دست، برای نسل‌ها.','جایی که خیال، راهی به امکان‌های تازه پیدا می‌کند.'],
 gallery:'لحظه‌هایی چون شعر',gallerySub:'زیبایی ایرانی، نگاهی جهانی.',viewGallery:'دیدن گالری',club:'باشگاه هما نت',clubSub:'زیبایی بیشتر، پیوندهایی عمیق‌تر، جهانی مهربان‌تر.',perks:['تجربه‌های ویژه','کشف‌های دل‌نشین','جامعه‌ای جهانی'],international:'از ایران، به دنیای شما',internationalSub:'با چشم‌انداز دلاریت آشنا شوید؛ برای نزدیک‌تر کردن هنر، فرهنگ و محصولات ایرانی به جهان.',learn:'کشف دنیای بین‌الملل',
 voices:'زیبایی، زبان مشترک ماست',voicesSub:'باورهایی که به تجربه‌های ما معنا می‌دهند.',quotes:['آهسته سفر کنیم، آدم‌ها را بشناسیم و با داستان‌ها برگردیم.','زیبایی از مراقبت آغاز می‌شود؛ از خودمان و از دنیای پیرامونمان.','هر اثر دست‌ساز، داستانی دارد که ارزش نگه‌داشتن دارد.'],quoteNames:['سفری عمیق‌تر','مراقبتی آگاهانه‌تر','میراثی زنده'],storyTitle:'ریشه در ایران، رو به جهان.',storyBody:'هما نت، سفر، زیبایی، صنایع‌دستی و فناوری خلاق را در جهانی مشترک کنار هم می‌آورد. الهام ما از فرهنگ ایرانی است: مهمان‌نوازی، توجه به جزئیات و این باور که زیبایی، آدم‌ها را به هم نزدیک می‌کند.',
 plan:'تجربهٔ خود را بسازید',choose:'دوست دارید چه چیزی را کشف کنید؟',name:'نام شما',email:'نشانی ایمیل',message:'کمی بیشتر برایمان بنویسید',send:'آماده‌سازی درخواست',requestNote:'فرم پیش‌نمایش است؛ اطلاعات ارسال یا ذخیره نمی‌شود. برای مرور درخواست، دکمه را بزنید.',success:'درخواست شما برای مرور آماده است',successBody:'در این پیش‌نمایش، درخواست فقط روی همین صفحه آماده شده و چیزی ارسال نشده است.',again:'ویرایش درخواست',tourismItems:['اصفهان و میراث زنده‌اش','شیراز، باغ و شعر','تخت‌جمشید و ایران کهن','یزد، باد و روشنایی'],beautyItems:['آیین‌های روزانهٔ زیبایی','الهام از طبیعت','تندرستی شخصی','مراقبت آگاهانه'],craftItems:['سفال و میناکاری','فرش دست‌باف','ظروف مسی','پارچه‌های ایرانی'],aiItems:['استودیو تولید محتوا','طراحی بصری هوشمند','روایت‌گری چندزبانه','خودکارسازی خلاق'],detailSub:'یک تجربه را انتخاب کنید تا مسیر دلخواهتان را بسازید.',next:'عکس بعدی',previous:'عکس قبلی',galleryLabel:'گالری تصاویر',picture:'عکس',currency:'واحد پول',about:'دربارهٔ هما نت',preview:'پیش‌نمایش عضویت',clubBody:'تجربه‌ها، مجموعه‌های تازه و داستان‌های فرهنگی مورد علاقه‌تان را انتخاب کنید و درخواست عضویت خود را آماده کنید.',contact:'آغاز یک گفت‌وگو',footerNotice:'عضویت در خبرنامه به‌زودی باز می‌شود.',formInterest:'موضوع مورد علاقه',selected:'تجربهٔ انتخاب‌شده'
 },
 ar: {
 nav:['الرئيسية','السياحة','الجمال','الحرف اليدوية','استوديو الذكاء الاصطناعي','قصتنا','تواصل معنا'],join:'انضم إلى نادينا',menu:'فتح القائمة',close:'إغلاق',eyebrow:'نادي العملاء',hero:'هما نت',sub:'سفر. جمال. ثقافة. غد أكثر إشراقاً.',line:'رحلة إلى الجمال، مستلهمة من الثقافة والمستقبل.',explore:'اكتشف عالمنا',story:'قصتنا',quote:'الجمال جسر بين الثقافات.',values:['تجارب أصيلة','جمالك المتجدد','حرف خالدة','مستقبل إبداعي'],worlds:'أربعة عوالم، رؤية واحدة',worldsSub:'حيث تلتقي روح إيران بغد أجمل.',titles:['السياحة','الجمال','الحرف اليدوية','استوديو الذكاء الاصطناعي'],descriptions:['رحلات استثنائية إلى قلب إيران.','أناقة طبيعية وطقوس مدروسة للعناية بك.','فن خالد وتراث حي مصنوع باليد.','حيث يلتقي الخيال بإمكانات جديدة.'],gallery:'لحظات كالشعر',gallerySub:'جمال إيراني، منظور عالمي.',viewGallery:'عرض المعرض',club:'نادي هما نت',clubSub:'جمال أكثر. روابط أعمق. عالم ألطف.',perks:['تجارب حصرية','اكتشافات ملهمة','مجتمع عالمي'],international:'من إيران إلى عالمك',internationalSub:'اكتشف رؤية دالاريت لتقريب الحرف والثقافة الإيرانية من العالم.',learn:'اكتشف الخدمات الدولية',voices:'حب مشترك للجمال',voicesSub:'القيم وراء كل تجربة.',quotes:['سافر بتأنٍّ. تعرّف إلى الناس. وعد إلى بيتك بقصصهم.','يبدأ الجمال بالعناية بأنفسنا وبالعالم من حولنا.','كل قطعة مصنوعة باليد تحمل قصة تستحق الحفظ.'],quoteNames:['سفر أعمق','عناية واعية','تراث حي'],storyTitle:'جذورنا في إيران، وآفاقنا العالم.',storyBody:'تجمع هما نت السفر والجمال والحرف والتكنولوجيا الإبداعية في عالم واحد. نستمد إلهامنا من الثقافة الإيرانية وكرم الضيافة وجمال التفاصيل والإيمان بأن الجمال يربط الناس.',plan:'صمّم تجربتك',choose:'ماذا تود أن تكتشف؟',name:'اسمك',email:'البريد الإلكتروني',message:'أخبرنا المزيد',send:'تحضير طلبي',requestNote:'نموذج تجريبي: لا تُرسل بياناتك ولا تُحفظ. أرسل النموذج لمراجعة طلبك.',success:'طلبك جاهز للمراجعة',successBody:'حُضّر طلبك محلياً في هذا العرض. لم يتم إرسال أي بيانات.',again:'تعديل الطلب',tourismItems:['أصفهان وتراثها الحي','شيراز وحدائقها وشعرها','برسبوليس وبلاد فارس القديمة','يزد والرياح والنور'],beautyItems:['طقوس الجمال اليومية','إلهام نباتي','العافية الشخصية','العناية الواعية'],craftItems:['خزف المينا','سجاد يدوي','نحاسيات تقليدية','منسوجات إيرانية'],aiItems:['استوديو المحتوى','تصميم بصري ذكي','قصص متعددة اللغات','أتمتة إبداعية'],detailSub:'اختر تجربة لتبدأ رحلتك الخاصة.',next:'الصورة التالية',previous:'الصورة السابقة',galleryLabel:'معرض الصور',picture:'صورة',currency:'العملة',about:'عن هما نت',preview:'معاينة العضوية',clubBody:'اختر التجارب والمجموعات والقصص التي تهمك، وحضّر طلب عضويتك.',contact:'ابدأ محادثة',footerNotice:'الاشتراك في النشرة قريباً.',formInterest:'اهتمامك',selected:'التجربة المختارة'
 }
};
export type Locale = keyof typeof copy;
