'use client';
import {useEffect, useRef, useState, type FormEvent} from 'react';
import {NextIntlClientProvider, useTranslations} from 'next-intl';
import {ArrowRight, ArrowLeft, Play, GlobeHemisphereWest, FlowerLotus, Cpu, Gift, Diamond, UsersThree, List, X, CaretLeft, CaretRight, Quotes, AirplaneTilt} from '@phosphor-icons/react';
import {Footer, localeDirection, defaultColumns} from '../src/components/footer';
import en from '../src/messages/en.json';
import fa from '../src/messages/fa.json';
import ar from '../src/messages/ar.json';
import {copy, type Locale} from './landing-copy';
import './landing.css';
import './editorial.css';
import {editorialCopy} from './editorial-copy';
import {BrandIntroduction,TravelCollection,CraftBeauty,CreativeStudio,Journal,BusinessPartnership,EnquiryProcess} from './BusinessSections';
import {completionCopy} from './completion-copy';
import {functionalCopy} from './function-copy';
import {sectionContent} from './section-content';
const translations={en,fa,ar};
const images=['tourism.jpg','beauty.jpg','craft.jpg','ai.jpg'];
const galleryImages=['tourism.jpg','beauty.jpg','craft.jpg','hero.jpg','ai.jpg','craft-wide.jpg','international.jpg'];
const sections=['tourism','beauty','handicrafts','ai'];
function requestKey(){const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;}
const ValueIcons=[GlobeHemisphereWest,FlowerLotus,Diamond,Cpu];
type Modal = 'story' | 'contact' | 'club' | 'gallery' | 'international' | 'info' | 'tracking' | 'journal' | number | null;

function Landing({locale,setLocale}:{locale:Locale;setLocale:(locale:Locale)=>void}) {
 const e=useTranslations('Editorial'); const [article,setArticle]=useState(1);
 const f=useTranslations('Completion'); const [copyNotice,setCopyNotice]=useState('');
 const u=useTranslations('Runtime'); const st=useTranslations('Sections'); const [infoKey,setInfoKey]=useState('help');
 const t=useTranslations('Landing'); const tf=useTranslations('Footer'); const [infoTitle,setInfoTitle]=useState('');
 const c=Object.fromEntries(Object.keys(copy.en).map(key=>[key,Array.isArray(copy.en[key as keyof typeof copy.en])?(copy.en[key as keyof typeof copy.en] as string[]).map((_,i)=>t(`${key}.${i}`)):t(key)])) as typeof copy.en;
 const [menu,setMenu]=useState(false); const [modal,setModal]=useState<Modal>(null); const [galleryIndex,setGalleryIndex]=useState(0);
 const [currency,setCurrency]=useState('USD'); const [interest,setInterest]=useState(''); const [submitted,setSubmitted]=useState(false);
 const [request,setRequest]=useState({name:'',email:'',message:''}); const dialog=useRef<HTMLDialogElement>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[code,setCode]=useState(''),[status,setStatus]=useState(''),[unsubscribe,setUnsubscribe]=useState('');
 const key=useRef(''),locked=useRef(false);
 const changeCurrency=(value:string)=>{setCurrency(value);try{localStorage.setItem('homay-currency',value);}catch{}};
 useEffect(()=>{try{const v=localStorage.getItem('homay-currency');if(v&&['USD','EUR','AED','IRR'].includes(v))setCurrency(v);}catch{}},[]);
 const subscribe=async(email:string)=>{setUnsubscribe('');const response=await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,locale,consent:true})});if(!response.ok)throw new Error(u('error'));const data=await response.json();if(data.unsubscribeToken)setUnsubscribe(data.unsubscribeToken);};
 const track=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');setStatus('');try{const response=await fetch('/api/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});if(!response.ok)throw new Error(u(response.status===404?'notFound':response.status===429?'rate':'error'));const data=await response.json();setStatus(data.status);}catch(e){setError(e instanceof Error&&[u('notFound'),u('rate'),u('error')].includes(e.message)?e.message:u('error'));}finally{setBusy(false);}};
 const copyCode=async()=>{try{await navigator.clipboard.writeText(code);setCopyNotice(u('copied'));}catch{setCopyNotice(f('copyFailed'));}};
 const receipt=()=>{const url=URL.createObjectURL(new Blob([`${u('success')}\n${u('trackingCode')}: ${code}\n${request.name}\n${request.email}\n${interest}`],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='homay-receipt.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const rtl=locale!=='en'; const Arrow=rtl?ArrowLeft:ArrowRight;
 const open=(value:Modal)=>{setSubmitted(false);setCopyNotice('');setError('');setStatus('');key.current='';setModal(value);setMenu(false);};
 useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=localeDirection(locale);},[locale]);
 useEffect(()=>{if(modal!==null) {dialog.current?.showModal();document.body.style.overflow='hidden';} else {dialog.current?.close();document.body.style.overflow='';} return()=>{document.body.style.overflow='';};},[modal]);
 const goTo=(index:number)=>{if(index===0) {window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setMenu(false);} else if(index<5) {open(index-1);} else open(index===5?'story':'contact');};
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setError('');try{key.current ||= requestKey();const response=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key.current},body:JSON.stringify({...request,kind:modal==='club'?'club':'enquiry',interest,locale,currency,consent:true})});if(!response.ok)throw new Error(u(response.status===429?'rate':'error'));const data=await response.json();setCode(data.trackingCode);setSubmitted(true);}catch(e){setError(e instanceof Error&&[u('notFound'),u('rate'),u('error')].includes(e.message)?e.message:u('error'));}finally{setBusy(false);locked.current=false;}};
 const enquire=(topic:string)=>{setInterest(topic);open('contact');};
 const allChoices=[c.tourismItems,c.beautyItems,c.craftItems,c.aiItems];
 const translatedName=locale==='ar'?'هماي سعادت':'همای سعادت';
 return <>
 <a href="#worlds" className="skip-link">{c.explore}</a>
 <div className="utility-bar"><span>{e('utility')}</span><div><a href="#partnership">{e('partnership')}</a><button onClick={()=>open('tracking')}>{u('tracking')}</button></div></div>
 <header className="site-header">
  <a href="#home" className="brand" aria-label="Homay Saadat"><img src="/assets/brand-mark.png" alt=""/><span><strong>Homay Saadat</strong><small lang="fa">همای سعادت</small></span></a>
  <nav aria-label={c.nav[0]} className="desktop-nav">{c.nav.map((label,i)=><button key={i} onClick={()=>goTo(i)} className={i===0?'active':''}><span>{label}</span></button>)}</nav>
  <div className="header-actions"><label className="sr-only" htmlFor="site-language">{u('language')}</label><select id="site-language" value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="en">EN</option><option value="fa">FA</option><option value="ar">AR</option></select><button className="gold-button join-header" onClick={()=>open('club')}>{c.join}<Arrow size={17}/></button><button className="mobile-menu icon-button" onClick={()=>setMenu(!menu)} aria-label={menu?c.close:c.menu} aria-expanded={menu} aria-controls="mobile-navigation">{menu?<X/>:<List/>}</button></div>
 </header>
 {menu&&<nav id="mobile-navigation" className="mobile-nav" onKeyDown={event=>{if(event.key==='Escape'){setMenu(false);document.querySelector<HTMLButtonElement>('.mobile-menu')?.focus();}}} aria-label={c.menu}>{c.nav.map((label,i)=><button key={i} onClick={()=>goTo(i)}>{label}<Arrow size={18}/></button>)}<button onClick={()=>open('club')}>{c.join}<Gift size={18}/></button></nav>}
 <main id="main" tabIndex={-1}>
 <section className="hero" id="home" aria-labelledby="hero-title">
  <img className="hero-photo" src="/assets/hero.jpg" alt={locale==='en'?'A woman in a teal Persian scarf beside the reflecting pool in Isfahan':locale==='fa'?'بانویی با شال ایرانی در کنار حوض میدان نقش جهان اصفهان':'امرأة بوشاح إيراني بجانب بركة في أصفهان'} fetchPriority="high"/>
  <div className="hero-shade"/>
  <div className="hero-content"><p className="eyebrow">{c.eyebrow}</p><h1 id="hero-title">{c.hero}</h1><p className="hero-sub">{c.sub}</p><p className="hero-fa" lang={locale==='en'?'fa':locale} dir={locale==='en'?'rtl':undefined}>{locale==='en'?copy.fa.line:c.line}</p><div className="hero-buttons"><a href="#worlds" className="gold-button">{c.explore}<Arrow size={24}/></a><button className="outline-button" onClick={()=>open('story')}>{c.story}<Arrow size={21}/></button></div></div>
  <p className="hero-quote">{locale==='en'&&<span lang="fa" dir="rtl">{copy.fa.quote}</span>}{c.quote}</p>
 </section>
 <div className="values-strip">{c.values.map((value,i)=>{const Icon=ValueIcons[i];return <div key={value}><Icon weight="thin"/><span>{value}</span></div>;})}</div>
 <BrandIntroduction onStory={()=>open('story')}/>
 <section className="worlds content-section" id="worlds" aria-labelledby="worlds-title">
  <div className="section-heading"><div><p className="eyebrow">{e('collection')}</p><h2 id="worlds-title">{c.worlds}</h2></div><p>{c.worldsSub}</p></div>
  <div className="world-grid">{c.titles.map((title,i)=><button id={sections[i]} className="world-card" key={title} onClick={()=>open(i)}><img src={`/assets/${images[i]}`} alt={title} loading="lazy"/><div className="card-shade"/><div className="world-copy"><span className="world-number">0{i+1}</span><h3>{title}</h3><p>{c.descriptions[i]}</p><span className="round-arrow"><Arrow size={21}/></span></div></button>)}</div>
 </section>
 <TravelCollection onEnquire={enquire}/>
 <CraftBeauty onEnquire={enquire} onCategory={open}/>
 <CreativeStudio onEnquire={enquire}/>
 <section className="gallery-section" aria-labelledby="gallery-title"><div className="gallery-heading"><h2 id="gallery-title">{c.gallery}</h2><p>{c.gallerySub}</p><button onClick={()=>{setGalleryIndex(0);open('gallery');}}>{c.viewGallery}<Arrow size={18}/></button></div><div className="gallery-strip">{galleryImages.map((src,i)=><button key={src} aria-label={`${c.picture} ${i+1}`} onClick={()=>{setGalleryIndex(i);open('gallery');}}><img src={`/assets/${src}`} alt={`${c.gallery} — ${i+1}`} loading="lazy"/></button>)}</div></section>
 <section id="club" className="club-banner"><img src="/assets/hero.jpg" className="club-photo" alt="" loading="lazy"/><div className="club-heading"><h2>{c.club}</h2>{locale==='en'&&<p lang="fa">{copy.fa.club}</p>}<p className="club-description">{c.clubSub}</p></div><div className="club-right"><div className="club-perks">{c.perks.map((p,i)=>{const Icon=[Gift,Diamond,UsersThree][i];return <div key={p}><Icon weight="thin" size={30}/><p>{p}</p></div>;})}</div><button className="gold-button" onClick={()=>open('club')}>{c.join}<Arrow size={19}/></button></div></section>
 <section className="international-section content-section" id="international"><div><p className="eyebrow">DALARIT</p><h2>{c.international}</h2><p>{c.internationalSub}</p><button className="text-button" onClick={()=>open('international')}>{c.learn}<Arrow size={20}/></button></div><button className="international-photo" onClick={()=>open('international')} aria-label={c.learn}><img src="/assets/international.jpg" alt={locale==='en'?'Air cargo and Persian-inspired packages':locale==='fa'?'بار هوایی و بسته‌های الهام‌گرفته از هنر ایرانی':'شحن جوي وطرود مستوحاة من الفن الإيراني'} loading="lazy"/><span><AirplaneTilt size={26}/>{c.international}</span></button></section>
 <Journal onArticle={index=>{setArticle(index);open('journal');}}/>
 <BusinessPartnership onEnquire={enquire}/>
 <EnquiryProcess/>
 <section className="landing-faq content-section" aria-labelledby="faq-title"><div><p className="eyebrow">{tf('columns.support')}</p><h2 id="faq-title">{f('faqTitle')}</h2><p>{f('faqIntro')}</p><button className="text-button" onClick={()=>open('tracking')}>{u('tracking')}<Arrow size={20}/></button></div><div className="faq-items">{[1,2,3,4].map(i=><details key={i}><summary>{f(`q${i}`)}</summary><p>{f(`a${i}`)}</p></details>)}</div></section>
 </main>
 <Footer variant="editorial" introduction={<div className="footer-introduction"><div><p className="eyebrow">{e('collection')}</p><h2>{e('footerTitle')}</h2><p>{e('footerText')}</p></div><div className="footer-contact-actions"><button className="gold-button" onClick={()=>open('contact')}>{e('footerContact')}<Arrow size={22}/></button><button className="footer-track" onClick={()=>open('tracking')}>{u('tracking')}<Arrow size={18}/></button></div></div>} signature={<div className="footer-signature"><span aria-hidden="true" lang="en" dir="ltr">Homay Saadat</span><p>{e('footerIdentity')}</p></div>} newsletterSuccessContent={unsubscribe?<div className="newsletter-cancellation"><p>{f('newsletterSave')}</p><a href={`/unsubscribe?token=${unsubscribe}`} rel="nofollow">{u('unsubscribe')}</a></div>:undefined} onSubscribe={subscribe} columns={defaultColumns.map(column=>({...column,links:column.links.map(link=>({...link,onClick:event=>{event.preventDefault(); const index=sections.indexOf(link.href.slice(1)); if(index>=0)open(index);else if(link.href==='/club')open('club');else if(['/global-shipping','/dalarit'].includes(link.href))open('international');else if(link.href==='/content'){document.getElementById('journal')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}else if(link.href==='/about')open('story');else if(['/booking','/concierge','/contact','/partners'].includes(link.href))enquire(tf(link.labelKey));else{setInfoTitle(tf(link.labelKey));setInfoKey(link.href.slice(1));open('info');}}}))}))} className="landing-footer" logo={<img src="/assets/brand-mark.png" alt="" width={58} height={58}/>} currency={currency} onCurrencyChange={changeCurrency} onLocaleChange={l=>setLocale(l as Locale)} homeHref="#home" resolveHref={path=>['/tourism','/beauty','/handicrafts','/ai'].includes(path)?path.replace('/','#'):path==='/'?'#home':path==='/content'?'#journal':path==='/club'?'#club':path==='/global-shipping'||path==='/dalarit'?'#international':'#about'} backToTopTargetId="main" year={2026}/>
 <dialog ref={dialog} className={`experience-dialog ${modal==='gallery'?'gallery-dialog':''}`} onKeyDown={event=>{if(modal==='gallery'&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();setGalleryIndex(i=>(i+(event.key==='ArrowRight'?1:6))%7);}}} onCancel={event=>{if(busy)event.preventDefault();else setModal(null);}} onClick={event=>{if(!busy&&event.target===event.currentTarget)setModal(null);}} aria-labelledby="dialog-title">
  <button className="dialog-close icon-button" disabled={busy} onClick={()=>setModal(null)} aria-label={c.close}><X size={24}/></button>
  {modal==='gallery'?<><h2 id="dialog-title">{c.gallery}</h2><img className="gallery-large" src={`/assets/${galleryImages[galleryIndex]}`} alt={`${c.picture} ${galleryIndex+1}`}/><div className="gallery-controls"><button className="icon-button" aria-label={c.previous} onClick={()=>setGalleryIndex((galleryIndex+6)%7)}><CaretLeft/></button><span>{galleryIndex+1} / 7</span><button className="icon-button" aria-label={c.next} onClick={()=>setGalleryIndex((galleryIndex+1)%7)}><CaretRight/></button></div></>:
  typeof modal==='number'?<><img className="dialog-cover" src={`/assets/${images[modal]}`} alt=""/><p className="eyebrow">{translatedName}</p><h2 id="dialog-title">{c.titles[modal]}</h2><p>{c.detailSub}</p><div className="experience-options">{allChoices[modal].map(choice=><button key={choice} onClick={()=>{setInterest(choice);open('contact');}}>{choice}<Arrow size={20}/></button>)}</div></>:
  modal==='journal'?<><img className="dialog-cover" src={`/assets/${['tourism.jpg','craft.jpg','ai.jpg'][article-1]}`} alt=""/><p className="eyebrow">{e(`journal${article}Tag`)}</p><h2 id="dialog-title">{e(`journal${article}Title`)}</h2><p className="story-body">{e(`journal${article}Body`)}</p><button className="editorial-link" onClick={()=>enquire(e(`journal${article}Title`))}>{e('footerContact')}<Arrow size={20}/></button></>:
  modal==='tracking'?<><h2 id="dialog-title">{u('tracking')}</h2><form className="request-form" onSubmit={track}><p>{u('lookupHint')}</p><label>{u('trackingCode')}<input disabled={busy} value={code} onChange={e=>setCode(e.target.value)} dir="ltr" required minLength={73} maxLength={73}/></label><button disabled={busy} className="gold-button">{busy?u('sending'):u('track')}</button>{status&&<p role="status">{u(status)}</p>}{error&&<p role="alert">{error}</p>}</form></>:
  modal==='info'?<><h2 id="dialog-title">{infoTitle}</h2><p className="story-body">{st(infoKey)}</p><button className="gold-button" onClick={()=>{setInterest(infoTitle);open('contact');}}>{u('infoCTA')}<Arrow size={20}/></button><button className="text-button" onClick={()=>open('tracking')}>{u('tracking')}</button></>:modal==='story'?<><img className="dialog-cover" src="/assets/hero.jpg" alt=""/><p className="eyebrow">{c.about}</p><h2 id="dialog-title">{c.storyTitle}</h2><p className="story-body">{c.storyBody}</p><button className="gold-button" onClick={()=>{setModal(null);document.getElementById('worlds')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}}>{c.explore}<Arrow size={20}/></button></>:
  modal==='international'?<><img className="dialog-cover" src="/assets/international.jpg" alt=""/><p className="eyebrow">DALARIT</p><h2 id="dialog-title">{c.international}</h2><p className="story-body">{c.internationalSub}</p><button className="gold-button" onClick={()=>{setInterest('Dalarit');open('contact');}}>{c.contact}<Arrow size={20}/></button></>:
  <><p className="eyebrow">{modal==='club'?u('preview'):c.contact}</p><h2 id="dialog-title">{submitted?u('success'):modal==='club'?c.club:c.plan}</h2>{submitted?<div className="request-review"><p>{u('successBody')}</p><label className="tracking-code">{u('trackingCode')}<input readOnly dir="ltr" value={code} onFocus={e=>e.target.select()}/></label><button className="text-button" onClick={copyCode}>{u('copy')}</button><p role="status">{copyNotice}</p><button className="text-button" onClick={receipt}>{u('download')}</button><button className="text-button" onClick={()=>open('tracking')}>{u('tracking')}</button><dl><dt>{c.name}</dt><dd>{request.name}</dd><dt>{c.email}</dt><dd dir="ltr">{request.email}</dd><dt>{c.formInterest}</dt><dd>{interest}</dd>{request.message&&<><dt>{c.message}</dt><dd>{request.message}</dd></>}</dl><button className="gold-button" onClick={()=>{setSubmitted(false);setRequest({name:'',email:'',message:''});key.current='';}}>{u('again')}</button></div>:<form className="request-form" onSubmit={submit} onChange={()=>{key.current='';}}>{modal==='club'&&<p>{u('clubBody')}</p>}<label>{c.formInterest}<select disabled={busy} value={interest} onChange={e=>setInterest(e.target.value)} required><option value="">{c.choose}</option>{Array.from(new Set([...c.titles,...allChoices.flat(),'Dalarit',...(interest?[interest]:[])])).map(v=><option key={v}>{v}</option>)}</select></label><div className="form-row"><label>{c.name}<input required minLength={2} maxLength={100} disabled={busy} autoComplete="name" value={request.name} onChange={e=>setRequest({...request,name:e.target.value})}/></label><label>{c.email}<input required maxLength={254} disabled={busy} type="email" autoComplete="email" dir="ltr" value={request.email} onChange={e=>setRequest({...request,email:e.target.value})}/></label></div><label>{c.message}<textarea maxLength={4000} disabled={busy} rows={3} value={request.message} onChange={e=>setRequest({...request,message:e.target.value})}/></label><p className="form-note">{u('requestNote')}</p><label className="consent"><input type="checkbox" required disabled={busy}/>{u('consent')}</label>{error&&<p role="alert">{error}</p>}<button disabled={busy} className="gold-button" type="submit">{busy?u('sending'):u('send')}<Arrow size={20}/></button></form>}</>}
 </dialog>
 </>;
}
export default function Page(){const [locale,setLocale]=useState<Locale>('en');useEffect(()=>{try{const v=localStorage.getItem('homay-locale');if(v==='en'||v==='fa'||v==='ar')setLocale(v);}catch{}},[]);const changeLocale=(value:Locale)=>{setLocale(value);try{localStorage.setItem('homay-locale',value);}catch{}};return <NextIntlClientProvider locale={locale} messages={{...translations[locale],Footer:{...translations[locale].Footer,newsletter:{...translations[locale].Footer.newsletter,notice:functionalCopy[locale].newsletterNotice,success:functionalCopy[locale].newsletterDone}},Editorial:editorialCopy[locale],Completion:completionCopy[locale],Runtime:functionalCopy[locale],Sections:sectionContent[locale],Landing:Object.fromEntries(Object.entries(copy[locale]).map(([key,value])=>[key,Array.isArray(value)?Object.fromEntries(value.map((item,i)=>[String(i),item])):value]))}} timeZone="UTC"><Landing locale={locale} setLocale={changeLocale}/></NextIntlClientProvider>;}
