#!/usr/bin/env bash
# Stage a merge with the installed release, preserving server-only changes.
set -Eeuo pipefail
app=/opt/homay/app
release="${1:?Pass the full Zibal release SHA}"
[[ "$release" =~ ^[a-f0-9]{40}$ ]] || exit 1
[[ "$(id -u)" == 0 ]] || { echo 'Run as root.'; exit 1; }
exec 9>/opt/homay/deploy-zibal.lock
flock -n 9 || { echo 'Another deployment is running.'; exit 1; }
cd "$app"
g() { git -c safe.directory="$app" "$@"; }
g cat-file -e "$release^{commit}"
# next-env.d.ts is generated by Next.js. All other local edits require review.
if [[ -n "$(g status --porcelain --untracked-files=normal | sed '/^ M next-env\.d\.ts$/d')" ]]; then
  echo 'STOP: additional local edits exist. No changes made.'
  g status --short
  exit 1
fi
systemctl is-active --quiet homay.service
systemctl is-active --quiet homay-worker.service
merchant=""
if [[ "${2:-}" != --skip-merchant ]]; then
  read -r -s -p 'Paste the Zibal merchant (hidden): ' merchant </dev/tty
  printf '\n' >/dev/tty
  [[ "$merchant" =~ ^[A-Za-z0-9_-]{6,200}$ && "$merchant" != zibal ]] || { echo 'Invalid production merchant.'; exit 1; }
fi
old_head="$(g rev-parse HEAD)"
deploy_dir="$(mktemp -d /opt/homay/zibal-release.XXXXXXXX)"
stage="$deploy_dir/stage"
mkdir -p "$deploy_dir/previous"
g diff --binary -- next-env.d.ts > "$deploy_dir/next-env.patch"
config_hash() {
  for config in .env .env.local .env.production .env.production.local; do
    [[ ! -f "$app/$config" ]] || sha256sum "$app/$config"
  done
}
initial_config="$(config_hash)"
stopped=0
advanced=0
generated_restored=0
old_node=0
old_build=0
new_node=0
new_build=0
schedule_changed=0
cleanup() {
  result=$?
  trap - EXIT
  unset merchant
  if ((result != 0 && stopped == 1)); then
    if ((schedule_changed)) && [[ -f "$deploy_dir/card-schedule-before.json" ]]; then
      runuser -u homay -- bash -c 'cd "$1" && NODE_ENV=production node --import tsx scripts/configure-card-schedule.ts --restore "$2"' bash "$app" "$deploy_dir/card-schedule-before.json" || { echo 'Schedule rollback needs review; services remain stopped.'; exit "$result"; }
    fi
    if ((advanced)); then
      g reset --merge "$old_head" || { echo 'Source rollback needs review; services remain stopped.'; exit "$result"; }
    fi
    if ((new_node)); then mv "$app/node_modules" "$deploy_dir/failed-node_modules" || true; fi
    if ((new_build)); then mv "$app/.next" "$deploy_dir/failed-next" || true; fi
    if ((old_node)); then mv "$deploy_dir/previous/node_modules" "$app/node_modules"; fi
    if ((old_build)); then mv "$deploy_dir/previous/.next" "$app/.next"; fi
    # Restore the generated local file only when source advancement replaced it.
    if ((generated_restored)) && [[ -s "$deploy_dir/next-env.patch" ]]; then
      g apply "$deploy_dir/next-env.patch" || true
    fi
    systemctl start homay.service homay-worker.service || true
    echo "Deployment failed. Previous code/build restored; records: $deploy_dir"
  elif ((result != 0 && advanced == 1)); then
    echo "Release is running; service diagnostics failed. Records: $deploy_dir"
  elif ((result != 0)); then
    echo "Staging failed; running services were not changed. Records: $deploy_dir"
  fi
  g worktree remove --force "$stage" 2>/dev/null || true
  exit "$result"
}
trap cleanup EXIT
g worktree add --detach "$stage" "$old_head"
if ! git -c safe.directory="$stage" -C "$stage" -c user.name='Homay Deploy' -c user.email='deploy@homanets.com' merge --no-ff --no-edit "$release"; then
  conflicts="$(git -c safe.directory="$stage" -C "$stage" diff --name-only --diff-filter=U)"
  while IFS= read -r conflict; do
    case "$conflict" in
      src/platform/finance.ts)
        cp "$stage/$conflict" "$deploy_dir/finance-conflict.txt"
        node - "$stage/$conflict" <<'HOMAY_FINANCE_FIX'
const fs = require('node:fs');
const path = process.argv[2];
const source = fs.readFileSync(path, 'utf8');
const blocks = [...source.matchAll(/^<<<<<<<[^\n]*\n([\s\S]*?)^=======\n([\s\S]*?)^>>>>>>>[^\n]*\n/gm)];
const compact = value => value.replace(/\s+/g, '');
const server = 'if (JSON.parse(saved.policy).binaryEngine !== "cards-v1" && schedule && schedule.mode !== "immediate")';
const release = 'if (saved.payment_method!=="company_credit" && schedule && schedule.mode !== "immediate")';
if (blocks.length !== 1 || compact(blocks[0][1]) !== compact(server) || compact(blocks[0][2]) !== compact(release)) {
  throw new Error('Unrecognized financial conflict; manual review required');
}
const result = source.replace(blocks[0][0], '    if (saved.payment_method !== "company_credit" && JSON.parse(saved.policy).binaryEngine !== "cards-v1" && schedule && schedule.mode !== "immediate")\n');
if (/^(<<<<<<<|=======|>>>>>>>)/m.test(result)) throw new Error('Remaining conflict');
fs.writeFileSync(path, result);
HOMAY_FINANCE_FIX
        ;;
      src/platform/seven-card-engine.test.ts)
        cp "$stage/$conflict" "$deploy_dir/seven-card-test-conflict.txt"
        git -c safe.directory="$stage" -C "$stage" show "${release}:$conflict" > "$stage/$conflict"
        ;;
      *) echo "STOP: unrecognized merge conflict: $conflict"; exit 1 ;;
    esac
    git -c safe.directory="$stage" -C "$stage" add -- "$conflict"
  done <<< "$conflicts"
  git -c safe.directory="$stage" -C "$stage" -c user.name='Homay Deploy' -c user.email='deploy@homanets.com' commit --no-edit
  echo 'Resolved reviewed conflict; preserved cards-v1 and company-credit exclusions.' 
fi
target="$(git -c safe.directory="$stage" -C "$stage" rev-parse HEAD)"
for config in .env .env.local .env.production .env.production.local; do
  if [[ -f "$app/$config" ]]; then cp "$app/$config" "$stage/$config"; chmod 600 "$stage/$config"; fi
done
chown -R homay:homay "$deploy_dir"
chmod 700 "$deploy_dir"
runuser -u homay -- nice -n 10 bash -c 'cd "$1" && npm ci --include=dev --no-audit --no-fund && npm run typecheck && npm exec -- vitest run src/platform/seven-card-engine.test.ts src/platform/checkout.test.ts src/platform/card-positions.test.ts src/platform/card-positions-ui.test.tsx src/platform/marketer-office.test.ts src/platform/company-members.test.ts src/platform/migrate-company-credit.test.ts src/platform/migrate-payment-methods.test.ts && DATABASE_PATH="$1/.deploy-validation.sqlite" npm run build' bash "$stage"
[[ "$(g rev-parse HEAD)" == "$old_head" && "$(config_hash)" == "$initial_config" ]] || { echo 'STOP: source or config changed during build.'; exit 1; }
systemctl stop homay.service homay-worker.service
stopped=1
runuser -u homay -- bash -c 'cd "$1" && npm run platform:backup -- "$2"' bash "$app" "$deploy_dir/database-backup"
# Generated next-env is saved above; tracked business files are not reset.
g restore -- next-env.d.ts
generated_restored=1
g merge --ff-only "$target"
advanced=1
if [[ -d "$app/node_modules" ]]; then mv "$app/node_modules" "$deploy_dir/previous/node_modules"; old_node=1; fi
if [[ -d "$app/.next" ]]; then mv "$app/.next" "$deploy_dir/previous/.next"; old_build=1; fi
mv "$stage/node_modules" "$app/node_modules"
new_node=1
mv "$stage/.next" "$app/.next"
new_build=1
runuser -u homay -- bash -c 'cd "$1" && npm run platform:setup' bash "$app"
schedule_changed=1
runuser -u homay -- bash -c 'cd "$1" && NODE_ENV=production node --import tsx scripts/configure-card-schedule.ts "$2"' bash "$app" "$deploy_dir/card-schedule-before.json"
if [[ -n "$merchant" ]]; then
printf '%s' "$merchant" | runuser -u homay -- bash -c 'cd "$1" && NODE_ENV=production npx tsx scripts/configure-zibal.ts' bash "$app"
fi
unset merchant
systemctl start homay.service homay-worker.service
systemctl is-active --quiet homay.service
systemctl is-active --quiet homay-worker.service
stopped=0
runuser -u homay -- bash -c 'cd "$1" && npm run services:check' bash "$app"
echo "Homay release installed. Existing service settings preserved. Backups: $deploy_dir"
echo 'Live payment and OTP delivery still require an end-to-end test.'
