"""Render the measured, isolated fixture results as a portable Persian report."""
from pathlib import Path
import json,html
root=Path(__file__).resolve().parents[1]
reports=[json.loads((root/'docs/club-scale-results.json').read_text()),json.loads((root/'docs/club-scale-left-results.json').read_text())]
results=[row for report in reports for row in report['results']]
rows=''.join(f"<tr><td>{r['members']:,}</td><td>{r['positions']:,}</td><td>{'متعادل' if r['scenario'].startswith('balanced') else 'متمرکز در چپ'}</td><td>{r['settlementMs']/1000:.2f} ثانیه</td><td>{r['reads']['positionTree']['p95Ms']:.1f} ms</td><td>{r['http']['failures']} / {r['http']['requests']}</td></tr>" for r in results)
page='''<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>آزمون شبکه هما نت</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f4f4ef;color:#1e2a44;font:16px/1.9 Tahoma,Arial,sans-serif}main{max-width:1100px;margin:auto;padding:28px 18px}h1{font-size:30px;margin:0}h2{font-size:21px}.intro{padding:24px;background:#133b3d;color:#fff;border-radius:22px}.intro p{margin:12px 0 0}.card{background:#fff;border:1px solid #dde4de;border-radius:18px;padding:20px;margin:20px 0}.table-wrap{overflow:auto}table{border-collapse:collapse;min-width:650px;width:100%;font-size:14px}td,th{padding:12px;text-align:right;border-bottom:1px solid #e5e8e4}label{display:flex;flex-direction:column;gap:5px}select,input,button{font:inherit;border:1px solid #ccd6d1;border-radius:10px;padding:8px;background:#fff;color:inherit}button{cursor:pointer;min-height:44px}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #e9784f;outline-offset:3px}.controls{display:flex;flex-wrap:wrap;align-items:end;gap:12px}.controls input{width:120px}.position-row{display:flex;justify-content:space-around;gap:8px;direction:ltr;margin:18px 0}.position{direction:rtl;display:flex;flex-direction:column;align-items:center;border:1px solid #80b79e;border-radius:12px;background:#e9f6ed;min-width:66px;padding:10px;flex:1;max-width:150px}.dot{border-radius:50%;width:12px;height:12px;background:#248a59;margin:6px}.position b{font-size:22px}.lines{height:18px;width:100%;display:block;stroke:#82a698;stroke-width:2;fill:none}.branches{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.branch{display:flex;flex-direction:column;text-align:center;background:#f4f7f4;font-size:12px}.branch.occupied{background:#e8f3ef;border-color:#74a591}.branch:disabled{cursor:default;opacity:.65}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.stats div{background:#f0f5f2;padding:12px;border-radius:10px}.stats strong{display:block;font-size:20px}.hint{font-size:13px;color:#536859}.state{padding:12px;border-radius:12px;background:#f0f5f2}.metrics{font-size:14px}.warning{border-right:4px solid #d68538;padding:14px;background:#fff5e5}.owner{margin:16px 0;display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap}@media(max-width:600px){main{padding:18px 12px}h1{font-size:25px}.card{padding:14px}.stats{grid-template-columns:1fr}.branches{grid-template-columns:repeat(2,1fr)}.position{min-width:50px;padding:8px 4px}.position b{font-size:19px}}
</style><main><header class="intro"><h1>آزمون شبکه هما نت</h1><p>۱۰۰۰ و ۱۰هزار حساب آزمایشی؛ هر حساب ۷ جایگاه فعال. موتور واقعی برنامه با یک محاسبه مستقل مقایسه شده است.</p></header>
<section class="card"><h2>نتایج اندازه‌گیری‌شده</h2><div class="table-wrap"><table><thead><tr><th>حساب</th><th>جایگاه</th><th>چیدمان</th><th>تسویه</th><th>خواندن نقشه · P95</th><th>خطا / درخواست HTTP</th></tr></thead><tbody>__ROWS__</tbody></table></div><p class="hint">برای هر سناریو ۱۲۰ درخواست API با همزمانی ۶ اجرا شده است. اعداد مربوط به محیط آزمایشی محلی‌اند.</p></section>
<section class="card"><h2>نقشه قابل بررسی</h2><div class="controls"><label>سناریو<select id="scenario"></select></label><label>شماره حساب<input type="number" min="0" id="member" value="0"></label><button id="open">نمایش</button><button id="parent">حساب بالادست</button></div><p class="hint">شماره حساب‌ها از صفر شروع می‌شود. برای ورود به نقشه یک زیرمجموعه، شاخه آن را لمس کنید.</p><div class="owner"><strong id="owner"></strong><span>● هفت جایگاه فعال با خرید آزمایشی</span></div><div id="map"></div><div id="branches" class="branches"></div><p id="selected" class="state" aria-live="polite"></p></section>
<section class="card"><h2>خلاصه مالی سناریو</h2><div id="stats" class="stats"></div><p class="hint">ووچر، پاداش نقدی و بازگشت وجه سیمرغ جدا هستند. حجم چند جایگاه نباید به‌عنوان فروش یکتای شبکه جمع شود.</p><div class="warning">این نتیجه، درآمد افراد یا پایداری اقتصادی در همه چیدمان‌ها را تضمین نمی‌کند. خریدها و تأیید پرداخت‌ها داده آزمایشی‌اند؛ بانک واقعی، نمایش Next.js، Nginx، کلادفلر و اینترنت کاربران در این آزمون بررسی نشده‌اند.</div></section>
<section class="card"><h2>موارد بررسی‌شده</h2><ul><li>محل دعوت دستی ثبت و پس از ورود عضو مصرف می‌شود.</li><li>هیچ خریدی برای جایگاه‌های خود خریدار حجم پورسانت ایجاد نمی‌کند.</li><li>حجم باقی‌مانده، نقدی، ووچر و فلش با محاسبه مستقل برابرند.</li><li>سقف ۱۵ میلیون تومان هر جایگاه رعایت می‌شود؛ هر هشتمین تطبیق ووچر است.</li><li>اجرای دوباره تسویه و آزادسازی، پاداش اضافه ایجاد نمی‌کند.</li><li>خواندن API با نشست معتبر موفق و دسترسی بدون نشست رد می‌شود.</li></ul></section></main>
<script>
const results=__DATA__,fmt=n=>Number(n).toLocaleString('fa-IR'),selector=document.getElementById('scenario'),input=document.getElementById('member');let current=0,selected=1;
const paths=['','L','R','LL','LR','RL','RR'],endpoints=['LLL','RRR','LRL','RLL','LLR','LRR','RLR','RRL'],parentPositions=[4,7,5,6,4,5,6,7];
results.forEach((r,i)=>{const option=document.createElement('option');option.value=i;option.textContent=fmt(r.members)+' حساب · '+(r.scenario.startsWith('balanced')?'متعادل':'متمرکز در چپ');selector.append(option)});
function draw(){const r=results[Number(selector.value)],left=r.scenario.startsWith('left'),fanout=left?2:8,n=r.members;current=Math.min(n-1,Math.max(0,current));input.max=n-1;input.value=current;document.getElementById('owner').textContent='حساب آزمایشی '+fmt(current);document.getElementById('parent').disabled=current===0;const sizes=Array(n).fill(1);for(let i=n-1;i>0;i--)sizes[Math.floor((i-1)/fanout)]+=sizes[i];
 const children=Array.from({length:8},(_,i)=>{const rank=left?(i===0?0:i===4?1:-1):i;const child=rank<0?-1:current*fanout+rank+1;return child>0&&child<n?child:null});const map=document.getElementById('map');map.replaceChildren();[[1],[2,3],[4,5,6,7]].forEach((row,index)=>{if(index){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 400 20');svg.classList.add('lines');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',index===1?'M200 0 L100 20 M200 0 L300 20':'M100 0 L50 20 M100 0 L150 20 M300 0 L250 20 M300 0 L350 20');svg.append(path);map.append(svg);}const line=document.createElement('div');line.className='position-row';row.forEach(desk=>{const button=document.createElement('button');button.className='position';button.innerHTML='<span class="dot"></span><b>'+fmt(desk)+'</b><small>فعال</small>';button.setAttribute('aria-label','جایگاه '+desk+' فعال');button.onclick=()=>{selected=desk;draw()};line.append(button)});map.append(line)});
 const branches=document.getElementById('branches');branches.replaceChildren();[1,5,3,6,4,7,8,2].forEach(ordinal=>{const child=children[ordinal-1],button=document.createElement('button');button.className='branch'+(child!==null?' occupied':'');button.disabled=child===null;const side=endpoints[ordinal-1].endsWith('L')?'چپ':'راست';button.textContent='شاخه '+fmt(ordinal)+' · جایگاه '+fmt(parentPositions[ordinal-1])+' · '+side+' · '+(child===null?'خالی':'حساب '+fmt(child)+' · '+fmt(sizes[child])+' عضو');button.onclick=()=>{current=child;selected=1;draw()};branches.append(button)});
 let l=0,rr=0;children.forEach((child,i)=>{if(child!==null&&endpoints[i].startsWith(paths[selected-1])){if(endpoints[i][paths[selected-1].length]==='L')l+=sizes[child];else rr+=sizes[child]}});document.getElementById('selected').textContent='جایگاه '+fmt(selected)+' · اعضای زیر شاخه چپ: '+fmt(l)+' · راست: '+fmt(rr);
 const stats=document.getElementById('stats');stats.replaceChildren();[['فروش یکتای حساب‌ها',r.salesToman],['پاداش نقدی',r.cashRewardToman],['ووچر',r.voucherToman],['بازگشت وجه سیمرغ',r.cashbackToman],['مبلغ فلش‌شده',r.flushedToman],['تعداد تطبیق پاداش‌دار',r.matches]].forEach(([label,value])=>{const div=document.createElement('div');div.textContent=label;const strong=document.createElement('strong');strong.textContent=fmt(value)+(label.startsWith('تعداد')?'':' تومان');div.append(strong);stats.append(div)})}
selector.onchange=()=>{current=0;selected=1;draw()};document.getElementById('open').onclick=()=>{current=Number(input.value)||0;selected=1;draw()};document.getElementById('parent').onclick=()=>{const fanout=results[Number(selector.value)].scenario.startsWith('left')?2:8;current=Math.max(0,Math.floor((current-1)/fanout));selected=1;draw()};draw();
</script></html>'''
page=page.replace('__ROWS__',rows).replace('__DATA__',json.dumps(results,ensure_ascii=False).replace('</','<\\/'))
(root/'docs/club-scale-viewer.html').write_text(page)
lines=['# آزمون مقیاس شبکه هما نت','',f"زمان اجرا: {reports[0]['generatedAt']}",'','هر حساب آزمایشی یک خرید پرداخت‌شده ۷۰ میلیون تومانی دارد و ۷ جایگاه آن فعال است. چیدمان متعادل با هشت ورودی و چیدمان متمرکز در چپ با دو ورودی بررسی شد. اطلاعات بانک و کاربران واقعی استفاده نشده است.','','| حساب | جایگاه | چیدمان | تسویه (ثانیه) | P95 نقشه (ms) | P95 HTTP (ms) | خطاهای HTTP |','|---:|---:|---|---:|---:|---:|---:|']
for r in results:lines.append(f"| {r['members']:,} | {r['positions']:,} | {'متعادل' if r['scenario'].startswith('balanced') else 'متمرکز در چپ'} | {r['settlementMs']/1000:.2f} | {r['reads']['positionTree']['p95Ms']:.2f} | {r['http']['p95Ms']:.2f} | {r['http']['failures']}/{r['http']['requests']} |")
lines+=['','برای هر سناریو ۱۲۰ درخواست HTTP محلی با همزمانی ۶ به مسیرهای نقشه، جست‌وجو، گزارش و دعوت فرستاده شد. نشست واقعی برنامه استفاده شد؛ درخواست بدون نشست باید ۴۰۱ برگرداند. این سرور آزمایشی از handler واقعی استفاده می‌کند و Next.js، Nginx، Cloudflare و اینترنت عمومی را شامل نمی‌شود.','','آزمون مستقل، تمام سفارش‌ها، حجم باقی‌مانده هر سمت و جایگاه، سقف هفتگی، نقدی، ووچر، فلش و تکرارنشدن پرداخت را کنترل می‌کند. هش‌های منابع آزمون در فایل JSON ثبت شده‌اند.','','اولین اجرای ۱۰هزار حساب قبل از بهینه‌سازی آماده‌سازی SQL، با SIGKILL متوقف شد و نتیجه موفق محسوب نمی‌شود. در اجرای اولیه ۱۰۰۰ حساب، تسویه ۸٫۶۶ ثانیه زمان برد. کش محدود دستورهای آماده SQL، داده یا پارامترهای کاربران را کش نمی‌کند؛ نقشه نیز حجم هفت جایگاه را با یک کوئری تجمیعی می‌خواند.','','این سناریوها اثبات درآمد، پایداری همه چیدمان‌ها یا ظرفیت سرور اصلی نیستند. توقف یا کندی کاربران واقعی هنوز به آزمون جداگانه روی مسیر شبکه و سرور نیاز دارد.','','اجرای مجدد:','','```bash','npm run platform:simulate -- 1000 10000','npm run platform:simulate -- 1000 --shape left-heavy --output docs/club-scale-left-results.json','python3 scripts/render-club-scale-report.py','```','']
(root/'docs/club-scale-report.md').write_text('\n'.join(lines))
