'use client';

import Localized from "../../../src/i18n/Localized";
import {useEffect,useState,type FormEvent} from 'react';
import '../style.css';
type Row={id:string;name?:string;email:string;kind?:string;interest?:string;message?:string;status:string;locale:string;currency?:string;created_at:string};
const statusLabel:Record<string,string>={new:'دریافت‌شده',in_progress:'در حال بررسی',closed:'بسته‌شده',pending:'ثبت‌شده؛ ایمیل تأیید نشده',unsubscribed:'لغو‌شده'};
export default function Admin(){
 const [logged,setLogged]=useState(false),[password,setPassword]=useState(''),[rows,setRows]=useState<Row[]>([]),[type,setType]=useState('requests'),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const response=await fetch(`/api/admin/records?type=${type}&page=${page}`,{cache:'no-store'});if(response.status===401){setLogged(false);return;}if(!response.ok)throw Error();const data=await response.json();setRows(data.rows);setTotal(data.total);}catch{setError('دریافت اطلاعات انجام نشد. دوباره تلاش کنید.');}finally{setBusy(false);}}
 useEffect(()=>{fetch('/api/admin/session',{cache:'no-store'}).then(r=>setLogged(r.ok)).catch(()=>setError('ارتباط با سرور برقرار نشد.'));},[]);
 useEffect(()=>{if(logged)void load();},[logged,type,page]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok){setError(d.error==='admin_not_configured'?'ابتدا npm run setup را اجرا کنید یا ADMIN_PASSWORD را در محیط سرور تنظیم کنید.':r.status===429?'تلاش‌های ورود زیاد است؛ یک دقیقه بعد دوباره امتحان کنید.':'رمز ورود معتبر نیست.');return;}setPassword('');setLogged(true);}catch{setError('ارتباط با سرور برقرار نشد.');}finally{setBusy(false);}}
 async function update(id:string,status:string){setBusy(true);setError('');try{const r=await fetch('/api/admin/records',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});if(!r.ok)throw Error();await load();}catch{setError('وضعیت ذخیره نشد.');}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{const r=await fetch('/api/admin/session',{method:'DELETE'});if(!r.ok)throw Error();setLogged(false);setRows([]);}catch{setError('خروج انجام نشد. دوباره تلاش کنید.');}finally{setBusy(false);}}
 function exportCSV(){const fields=['id','name','email','kind','interest','message','status','locale','currency','created_at'] as const;const escape=(v:string)=>'"'+(/^[=+@\-\t\r\n]/.test(v)?"'"+v:v).replaceAll('"','""')+'"';const csv='\ufeff'+fields.join(',')+'\r\n'+rows.map(r=>fields.map(f=>escape(String(r[f]??''))).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`homay-${type}-page-${page}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <Localized><main className="admin" dir="rtl"><header><div><p>HOMAY SAADAT</p><h1>مدیریت درخواست‌ها</h1></div><a href="/">بازگشت به سایت</a>{logged&&<button onClick={logout}>خروج</button>}</header><p role="alert">{error}</p>{!logged?<form onSubmit={login} className="admin-login"><h2>ورود مدیر</h2><label>رمز مدیریت<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?'در حال بررسی…':'ورود'}</button></form>:<><div className="admin-tools"><label>نمایش<select value={type} onChange={e=>{setType(e.target.value);setPage(1);}}><option value="requests">درخواست خدمات و باشگاه</option><option value="subscribers">درخواست‌های خبرنامه</option></select></label><button disabled={busy} onClick={load}>تازه‌سازی</button><button disabled={!rows.length||busy} onClick={exportCSV}>دریافت CSV همین صفحه</button><span>{total} مورد</span></div><div className="admin-table" aria-busy={busy}><table><thead><tr><th>شناسه و زمان</th><th>نام و ایمیل</th><th>موضوع و پیام</th><th>وضعیت</th></tr></thead><tbody>{rows.map(r=><Localized key={r.id}><tr><td><code>{r.id}</code><p>{new Date(r.created_at).toLocaleString('fa-IR')}</p><small>{r.kind==='club'?'باشگاه':r.kind==='enquiry'?'درخواست خدمت':'خبرنامه'}</small></td><td>{r.name}<p dir="ltr">{r.email}</p><small>{r.locale} · {r.currency}</small></td><td><strong>{r.interest}</strong><p className="message">{r.message}</p></td><td>{type==='requests'?<select aria-label={`وضعیت ${r.id}`} disabled={busy} value={r.status} onChange={e=>update(r.id,e.target.value)}>{['new','in_progress','closed'].map(s=><Localized key={s}><option value={s}>{statusLabel[s]}</option></Localized>)}</select>:statusLabel[r.status]}</td></tr></Localized>)}</tbody></table>{!rows.length&&!busy&&<p>هنوز موردی ثبت نشده است.</p>}</div><footer><button disabled={page===1||busy} onClick={()=>setPage(page-1)}>قبلی</button><span>صفحهٔ {page}</span><button disabled={page*50>=total||busy} onClick={()=>setPage(page+1)}>بعدی</button></footer></>}</main></Localized>;
}
