import type { Field } from "./Widgets";
import { craftCategories } from "../commerce/craft-taxonomy";
const section = (name: string, label: string, sectors?: string[]): Field => ({
  name,
  label,
  type: "section",
  sectors,
  full: true,
});
const field = (
  name: string,
  label: string,
  type = "text",
  sectors?: string[],
  max?: number,
): Field => ({
  name: "detail_" + name,
  label,
  type,
  sectors,
  required: false,
  max: max ?? (type === "number" ? 1e9 : type === "textarea" ? 5000 : 200),
  min: type === "number" ? 0 : undefined,
  full: type === "textarea",
});
export const extendedCatalogFields: Field[] = [
  section("identity", "شناسه، برند و تنوع کالا"),
  field("sku", "کد انبار SKU", "text", undefined, 80),
  field("barcode", "بارکد"),
  field("family", "کد خانواده محصول", "text"),
  field("brand", "برند"),
  field("origin", "کشور سازنده"),
  field("supplier", "تأمین‌کننده (فقط مدیریت)"),
  field("color", "رنگ"),
  field("size", "اندازه / سایز"),
  field("material", "جنس"),
  section("commercial", "قیمت‌گذاری و انبار"),
  field("cost", "بهای خرید (تومان؛ فقط مدیریت)", "number", undefined, 1e12),
  field("comparePrice", "قیمت قبل از تخفیف (تومان)", "number", undefined, 1e12),
  field("lowStock", "آستانه هشدار کمبود", "number"),
  section("logistics", "ارسال و خدمات پس از فروش", ["beauty", "craft", "leather"]),
  field("weightGrams", "وزن بسته (گرم)", "number", ["beauty", "craft", "leather"]),
  field("dimensions", "ابعاد بسته (سانتی‌متر)", "text", ["beauty", "craft", "leather"]),
  field("shippingNote", "شرایط ارسال", "textarea", ["beauty", "craft", "leather"]),
  field("warranty", "ضمانت و شرایط مرجوعی", "textarea"),
  section("tour", "اطلاعات سفر و اقامت", ["tourism"]),
  field("destination", "مقصد", "text", ["tourism"]),
  field("departure", "مبدأ حرکت", "text", ["tourism"]),
  field("startsOn", "تاریخ شروع سفر", "date", ["tourism"]),
  field("endsOn", "تاریخ پایان سفر", "date", ["tourism"]),
  field("nights", "تعداد شب اقامت", "number", ["tourism"]),
  field("accommodation", "اقامتگاه و درجه", "text", ["tourism"]),
  field("meals", "وعده‌های غذایی", "text", ["tourism"]),
  field("itinerary", "برنامه روزانه سفر", "textarea", ["tourism"]),
  field("inclusions", "خدمات شامل قیمت", "textarea", ["tourism"]),
  field("exclusions", "خدمات خارج از قیمت", "textarea", ["tourism"]),
  section("cosmetics", "مشخصات آرایشی و بهداشتی", ["beauty"]),
  field("skinType", "نوع پوست / مو", "text", ["beauty"]),
  field("volume", "حجم / وزن خالص", "text", ["beauty"]),
  field("expiresOn", "تاریخ انقضا", "date", ["beauty"]),
  field("ingredients", "ترکیبات", "textarea", ["beauty"]),
  field("usage", "روش مصرف", "textarea", ["beauty"]),
  field("warnings", "هشدارهای مصرف", "textarea", ["beauty"]),
  section("craftTaxonomy", "دسته‌بندی صنایع‌دستی", ["craft", "leather"]),
  {
    ...field("craftCategory", "دسته محصول", "select", ["craft", "leather"]),
    options: [["", "بدون دسته"], ...craftCategories.map((c): [string, string] => [c.id, c.name])],
  },
  {
    ...field("craftTechnique", "تکنیک کار مس", "select", ["craft"]),
    options: [["", "—"], ...(craftCategories[0].techniques || []).map((t): [string, string] => [t.id, t.name])],
  },
  {
    ...field("craftItem", "کاربری محصول", "select", ["craft", "leather"]),
    options: [
      ["", "—"],
      ...[...new Map(craftCategories.flatMap((c) => c.items || []).map((i) => [i.id, i.name])).entries()],
    ],
  },
  section("craftsmanship", "شناسنامه صنایع‌دستی", ["craft", "leather"]),
  field("artisan", "نام هنرمند / کارگاه", "text", ["craft", "leather"]),
  field("technique", "تکنیک ساخت", "text", ["craft", "leather"]),
  field("care", "روش نگهداری", "textarea", ["craft", "leather"]),
  section("intelligence", "جزئیات پلن هوش مصنوعی", ["ai"]),
  field("aiProvider", "ارائه‌دهنده سرویس", "text", ["ai"]),
  field("aiModel", "مدل‌های قابل استفاده", "text", ["ai"]),
  field("seats", "تعداد کاربر مجاز", "number", ["ai"]),
  field("quota", "سهمیه مصرف و محدودیت‌ها", "text", ["ai"]),
  field("delivery", "روش تحویل و فعال‌سازی", "textarea", ["ai"]),
  field("requirements", "پیش‌نیازهای استفاده", "textarea", ["ai"]),
  section("presentation", "ارائه محصول و ترجمه‌ها"),
  field("features", "ویژگی‌های شاخص؛ هر خط یک مورد", "textarea"),
  field("video", "نشانی ویدئو HTTPS", "url", undefined, 1000),
  field("titleEn", "عنوان انگلیسی"),
  field("descriptionEn", "توضیحات انگلیسی", "textarea"),
  field("titleAr", "عنوان عربی"),
  field("descriptionAr", "توضیحات عربی", "textarea"),
  field("seoTitle", "عنوان سئو", "text", undefined, 70),
  field("seoDescription", "توضیح متا", "textarea", undefined, 170),
];
