"use client";
import {useEffect,useState} from "react";
import {amount,date,RecordData} from "./client";
import {DataState,Stat,useData} from "./Widgets";
export function LaunchDashboard({refresh,onNavigate}:{refresh:number;onNavigate:(tab:string)=>void}) {
  const [tick,setTick]=useState(0);
  useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')setTick(v=>v+1);},30000);return()=>clearInterval(timer);},[]);
  const state=useData('admin/launch-dashboard',refresh+tick);
  const wait=(oldest:string,at:string)=>{const minutes=Math.max(0,Math.floor((Date.parse(at)-Date.parse(oldest))/60000));return minutes<60?amount(minutes)+' دقیقه':amount(Math.floor(minutes/60))+' ساعت';};
  return <section className="portal-card"><h2>کنترل شروع فعالیت</h2><DataState state={state}>{d=><><p>آمار امروز از نیمه‌شب تهران: {date(d.since)}</p><p className="portal-muted">به‌روزرسانی: {date(d.generatedAt)} · بررسی خودکار هر ۳۰ ثانیه در صفحه باز</p><div className="portal-stats"><Stat label="جایگاه‌های فعال فعلی" value={d.activePositions} unit="جایگاه"/><Stat label="ثبت‌نام امروز" value={d.registrationsToday} unit="عضو"/><Stat label="ثبت‌نام هفت روز اخیر" value={d.registrationsWeek} unit="عضو"/><Stat label="سفارش پرداخت‌شده امروز" value={d.paidOrdersToday} unit="سفارش"/></div><ul className="launch-backlog">{[['pendingPayments','سفارش‌های در انتظار پرداخت','orders'],['bankReviews','اطلاعات بانکی در انتظار بررسی','withdrawals'],['support','تیکت‌های منتظر پشتیبانی','tickets'],['withdrawals','برداشت‌های در انتظار پرداخت','withdrawals']].map(([key,label,tab])=>{const row=d[key] as RecordData;return <li key={key}><div><strong>{label}: {amount(row.count)}</strong><small>قدیمی‌ترین درخواست: {row.oldest?date(row.oldest)+' · انتظار '+wait(row.oldest,d.generatedAt):'درخواستی در انتظار نیست'}</small></div><button className="portal-button secondary" onClick={()=>onNavigate(tab)}>بررسی</button></li>})}</ul><h3>پردازش مالی</h3><p>محاسبه پلن: {d.health.financial.enabled?'روشن':'خاموش'}</p><div role="status"><p>پردازش پس‌زمینه: {d.health.worker.healthy?'فعال':'نیازمند بررسی'} · آخرین اجرای موفق: {d.health.worker.lastSuccess?date(d.health.worker.lastSuccess):'هنوز ثبت نشده'}</p><p>بررسی محاسبه و آزادسازی: {d.health.financial.healthy?'فعال':'نیازمند بررسی'} · آخرین بررسی موفق: {d.health.financial.lastSuccess?date(d.health.financial.lastSuccess):'پس از نصب این نسخه ثبت می‌شود'}</p></div>{(!d.health.worker.healthy||!d.health.financial.healthy)&&<p className="portal-error" role="alert">اجرای موفق اخیر ثبت نشده است؛ وضعیت سرویس پردازش و گزارش خطا را بررسی کنید.</p>}{d.health.financial.lastFailure&&<p className="portal-error">آخرین خطای بررسی مالی: {date(d.health.financial.lastFailure)}</p>}<p>آخرین تسویه هفتگی: {d.latestSettlement?date(d.latestSettlement.settled_at):'هنوز هفته‌ای تسویه نشده'} · پاداش‌های سررسیدشده در انتظار آزادسازی: {amount(d.rewardRelease.count)}</p><p className="portal-muted">موفقیت بررسی به معنی تسویه یک هفته جدید نیست. قطع دسترسی عمومی سایت باید از میزبان مستقل پایش شود؛ این صفحه هنگام قطع سایت در دسترس نخواهد بود.</p><button className="portal-button secondary" onClick={()=>onNavigate('binary')}>گزارش مالی</button><p className="portal-muted">تلاش‌های ناموفق ثبت‌شده درگاه‌ها در هفت روز اخیر: {amount(d.failedGatewayAttempts)} · لغوشده‌ها: {amount(d.cancelledGatewayAttempts)}. سفارش پرداخت‌نشده به‌تنهایی نشانه خطای درگاه نیست.</p></>}</DataState></section>;
}
