import {
  Bell,
  BookOpen,
  CreditCard,
  Gift,
  GitBranch,
  Heart,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  MapPin,
  Package,
  Plane,
  ShieldCheck,
  ShoppingBag,
  Store,
  Target,
  UserRound,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/** One icon per member tab, shown in the account sidebar. */
export const memberTabIcons: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  wishlist: Heart,
  notifications: Bell,
  tickets: LifeBuoy,
  catalog: ShoppingBag,
  orders: Package,
  "travel-cards": Plane,
  subscriptions: BookOpen,
  "seven-card-plan": Layers,
  network: Users,
  binary: GitBranch,
  loyalty: Gift,
  missions: Target,
  wallet: Wallet,
  commissions: CreditCard,
  profile: UserRound,
  addresses: MapPin,
  security: ShieldCheck,
  merchant: Store,
};
