// @vitest-environment node
import {beforeAll,afterAll,it,expect,vi} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {handle} from './api';
import {run,one,now,platformDb} from './schema';
import {saveSetting} from './providers';
import {session,SESSION_COOKIE,totp} from './security';
import {configureSevenLevelPlan} from './card-positions';
import {runCardSettlement,weekStartAt} from './seven-card-engine';
import {testIdentity} from './test-identity';
const dir=mkdtempSync(join(tmpdir(),'homay-journey-'));
let root:string,cookie:string,product:string,code:string;
const provider=vi.fn(async(url:string,init:RequestInit)=>{if(url.includes('resend')){code=JSON.parse(String(init.body)).text.match(/\d{6}/)[0];return Response.json({id:randomUUID()});}if(url.endsWith('/request'))return Response.json({result:100,trackId:123456789});if(url.endsWith('/verify'))return Response.json({result:100,status:1,amount:100000000});throw Error('Unexpected provider');});
const request=(path:string,method='GET',data?:unknown,auth='')=>handle(new Request('https://homay.test/api/platform/'+path,{method,headers:{origin:'https://homay.test',host:'homay.test',cookie:auth,'content-type':'application/json'},...(method==='GET'?{}:{body:JSON.stringify(data)})}),path.split('?')[0].split('/'));
beforeAll(()=>{
 process.env.DATABASE_PATH=join(dir,'journey.sqlite');process.env.PLATFORM_MASTER_KEY='a'.repeat(64);process.env.APP_ORIGIN='https://homay.test';
 root=randomUUID();product=randomUUID();run("INSERT INTO p_users(id,name,password,role,referral_code,created_at,last_seen,signup_ip) VALUES(?,?,?,'superadmin','journey-root',?,?,?)",root,'Journey root','unused',now(),now(),'test');run('INSERT INTO p_wallets(user_id) VALUES(?)',root);
 run("INSERT INTO p_products(id,title,description,vertical,subtype,price,stock,cancel_hours,published,created_at,updated_at) VALUES(?,?,?,'ai','subscription',10000000,100,0,1,?,?)",product,'Journey product','',now(),now());
 saveSetting('seven_card_schedule_version','2026-10-06');configureSevenLevelPlan();saveSetting('company_position_permanent_owner',root);run("INSERT INTO p_company_positions VALUES(?,7,?,'2050-01-01T00:00:00Z',?,?)",root,now(),root,'qualified');cookie=SESSION_COOKIE+'='+session(root,'test');
 saveSetting('resend_key','test-key',true);saveSetting('email_from','test@homay.test');saveSetting('zibal_merchant','fixture-merchant',true);saveSetting('commission_policy',JSON.stringify({directBps:0,levels:[],binaryBps:0,maxPayoutBps:0,warningBps:5000,criticalBps:8000,withdrawMin:1,withdrawMax:1000000000,paused:false}));
 saveSetting('seven_card_plan_draft',JSON.stringify({revision:1,decisions:{overflow:'flush',counterScope:'member',voucherCountsTowardCap:true,topology:'own-desks',purchaseCredit:'purchase-value',weekStart:1}}));saveSetting('seven_card_live','1');saveSetting('seven_card_budget_unlimited','1');saveSetting('seven_card_live_since',String(Date.now()));
 vi.stubGlobal('fetch',provider);
});
afterAll(()=>{vi.unstubAllGlobals();platformDb().close();rmSync(dir,{recursive:true,force:true});});
it('runs real authenticated registration, manual placement, verified purchase, activation and volume exactly once',async()=>{
 expect((await request('referral/placement','POST',{ordinal:1},cookie)).status).toBe(200);
 const target='journey-member@test.example';const sent=await(await request('auth/otp','POST',{target,purpose:'register'})).json();
 const verification=await(await request('auth/verify-email','POST',{target,challenge:sent.challenge,code})).json();
 const registered=await request('auth/register','POST',{target,password:'test-strong-password-2026',details:{firstName:'عضو',lastName:'آزمون',country:'ایران',city:'تهران'},termsAccepted:true,privacyAccepted:true,adultConfirmed:true,termsVersion:'2026-09-20-v1',...testIdentity(),verificationToken:verification.verificationToken,totp:totp(verification.secret),invitationMode:'with-code',referral:'journey-root'});
 expect(registered.status).toBe(200);const auth=registered.headers.get('set-cookie')!.split(';')[0],user=(await registered.json()).user;
 expect(one('SELECT sponsor_id,ordinal FROM p_card_direct_positions WHERE child_id=?',user.id)).toMatchObject({sponsor_id:root,ordinal:1});expect(one('SELECT * FROM p_referral_endpoint_choice WHERE user_id=?',root)).toBeUndefined();
 const created=await request('orders','POST',{productId:product,quantity:1,method:'zibal',idempotencyKey:randomUUID()},auth);expect(created.status).toBe(201);const order=await created.json();
 expect((await request(`orders/${order.id}/payment`,'POST',{},auth)).status).toBe(200);
 const callback=()=>request('payment/callback?gateway=zibal&success=1&trackId=123456789');expect((await callback()).status).toBe(303);expect((await callback()).status).toBe(303);
 expect(provider.mock.calls.filter(([url])=>url.endsWith('/verify'))).toHaveLength(1);
 const retry=await request(`orders/${order.id}/payment`,'POST',{},auth);expect(await retry.json()).toMatchObject({status:'paid'});
 expect(provider.mock.calls.filter(([url])=>url.endsWith('/request'))).toHaveLength(1);
 const detail=await(await request(`orders/${order.id}`,'GET',undefined,auth)).json();expect(detail.activationReceipt).toMatchObject({activePositions:[1],referralCapacity:2,weeklyCapToman:15000000});
 expect((await request(`orders/${order.id}`,'GET',undefined,cookie)).status).toBe(404);
 const ticket=await request('tickets','POST',{subject:'پیگیری سفارش خرید',category:'order',priority:'normal',body:'درخواست بررسی وضعیت این سفارش',orderId:order.id,idempotencyKey:randomUUID()},auth);expect(ticket.status).toBeLessThan(300);
 expect(one('SELECT order_id FROM p_tickets WHERE id=?',(await ticket.json()).id)!.order_id).toBe(order.id);
 const denied=await request('tickets','POST',{subject:'سفارش عضو دیگر',category:'order',priority:'normal',body:'درخواست بررسی وضعیت سفارش دیگر',orderId:order.id,idempotencyKey:randomUUID()},cookie);expect(denied.status).toBe(404);
 const dashboard=await(await request('dashboard','GET',undefined,auth)).json();expect(dashboard.club).toMatchObject({desks:1,weeklyCapToman:15000000});expect(dashboard.invitation.state).toBe('placement_required');
 const cutoff=weekStartAt(Date.now(),1)+7*86400000+3600000;runCardSettlement(cutoff);runCardSettlement(cutoff);
 expect(one("SELECT COUNT(*) n,SUM(volume) volume FROM p_card_position_lots WHERE user_id=? AND desk=4 AND leg='left'",root)).toMatchObject({n:1,volume:10000000});
 expect(one('SELECT pending FROM p_wallets WHERE user_id=?',user.id)!.pending).toBe(0);
 expect(one("SELECT COUNT(*) n FROM p_notifications WHERE user_id=? AND title='پرداخت سفارش تأیید شد'",user.id)!.n).toBe(1);
 expect((await request('binary?user='+root,'GET',undefined,auth)).status).toBe(403);
});
