// @vitest-environment node
import {beforeAll,afterAll,it,expect} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {randomUUID} from 'node:crypto';
import {handle} from './api';import {run,one,now,platformDb} from './schema';import {hash} from '../server/http';import {TERMS_VERSION,registrationSchema} from './registration-model';import {saveSetting} from './providers';
const dir=mkdtempSync(join(tmpdir(),'homay-registration-'));let sponsor:string;
function request(path:string,method='GET',payload?:unknown,cookie=''){return handle(new Request('https://homay.test/api/platform/'+path,{method,headers:{origin:'https://homay.test',host:'homay.test','Content-Type':'application/json',cookie},...(method==='GET'?{}:{body:JSON.stringify(payload)})}),path.split('/'));}
function payload(){const challenge=randomUUID();run('INSERT INTO p_otp VALUES(?,?,?,?,?,0,0,?)',challenge,'member@example.test','register',hash(challenge+':123456'),Date.now()+300000,now());return {target:'member@example.test',password:'a-test-password-123',challenge,code:'123456',details:{firstName:'عضو',lastName:'آزمون',country:'ایران',city:'شیراز',occupation:'هنرمند',language:'fa',interests:['craft']},termsAccepted:true,privacyAccepted:true,adultConfirmed:true,termsVersion:TERMS_VERSION,marketingConsent:false,referral:'sponsor-code'};}
beforeAll(()=>{process.env.DATABASE_PATH=join(dir,'test.sqlite');process.env.APP_ORIGIN='https://homay.test';sponsor=randomUUID();run("INSERT INTO p_users(id,name,password,referral_code,created_at,last_seen,signup_ip) VALUES(?,'معرف','unused','sponsor-code',?,?,'test')",sponsor,now(),now());});
afterAll(()=>{platformDb().close();rmSync(dir,{recursive:true,force:true});});
it('rejects missing consent and malformed personal details on server and shared schema',async()=>{const d=payload();expect(registrationSchema.safeParse({...d,termsAccepted:false}).success).toBe(false);expect((await request('auth/register','POST',{...d,privacyAccepted:false})).status).toBe(400);expect((await request('auth/register','POST',{...d,details:{...d.details,city:''}})).status).toBe(400);expect(one('SELECT used FROM p_otp WHERE id=?',d.challenge)!.used).toBe(0);});
it('validates referrals without exposing sponsor data or allowing blocked sponsors',async()=>{expect(await(await request('referrals/check','POST',{code:'SPONSOR-CODE'})).json()).toEqual({valid:true});run('UPDATE p_users SET blocked=1 WHERE id=?',sponsor);expect(await(await request('referrals/check','POST',{code:'sponsor-code'})).json()).toEqual({valid:false});const d=payload();expect((await request('auth/register','POST',d)).status).toBe(400);expect(one('SELECT used FROM p_otp WHERE id=?',d.challenge)!.used).toBe(0);run('UPDATE p_users SET blocked=0 WHERE id=?',sponsor);});
it('requires actual OTP and persists details, immutable consent and sponsor in the same signup',async()=>{const d=payload();expect((await request('auth/register','POST',{...d,code:'999999'})).status).toBe(401);const r=await request('auth/register','POST',d);expect(r.status).toBe(200);const u=(await r.json()).user;expect(u.name).toBe('عضو آزمون');expect(u.preferences.email).toBe(false);expect(one('SELECT sponsor_id FROM p_users WHERE id=?',u.id)!.sponsor_id).toBe(sponsor);const consent=one('SELECT * FROM p_consents WHERE user_id=?',u.id)!;expect(consent.version).toBe(TERMS_VERSION);expect(consent.marketing).toBe(0);expect(()=>run('UPDATE p_consents SET marketing=1 WHERE user_id=?',u.id)).toThrow();const cookie=r.headers.get('set-cookie')!.split(';')[0];expect((await request('member-details')).status).toBe(401);const profile=await(await request('member-details','GET',undefined,cookie)).json();expect(JSON.parse(profile.profile.details).city).toBe('شیراز');expect(profile.profile.contact_verified_at).toBeTruthy();expect((await request('member-details','PATCH',{...d.details,city:'تهران'},cookie)).status).toBe(200);expect(JSON.parse(one('SELECT details FROM p_member_details WHERE user_id=?',u.id)!.details).city).toBe('تهران');expect(one("SELECT COUNT(*) n FROM p_audit WHERE action='member.details'")!.n).toBe(1);});
it('publishes only actual configured commission policy and no financial health internals',async()=>{expect(await(await request('income-plan')).json()).toEqual({configured:false});saveSetting('commission_policy',JSON.stringify({directBps:500,levels:[],binaryBps:0,maxPayoutBps:1000,warningBps:4000,criticalBps:6000,withdrawMin:1000,withdrawMax:1000000,paused:false}));const d=await(await request('income-plan')).json();expect(d.directBps).toBe(500);expect(d.ranks).toEqual([]);expect(d.criticalBps).toBeUndefined();});
